#!/usr/bin/env python3
"""gen-di-facts.py — DI (Diablo Immortal) facts for megaprobe 2026-07-12
23 records: all corpus=di rows (all negative=False in source; 3 are progression-system records)
Post-cutoff (2026 era): di-warlock-launch, di-bombardment-wizard-pvp, di-spiritform-druid-pvp (3)
Meta-system records: di-essence-transfer, di-resonance-awakening, di-inferno-ladder (3 — delivery=other)
Conf strata: launch-2022 = 0.75-0.85 | bk-2023 = 0.70-0.75 | tempest-2024 = 0.60-0.70
             druid-2025 = 0.55-0.65 | post-cutoff 2026 = cap 0.50
"""
import json

OUT = "agentic_orchestration/legolas/research/megaprobe-2026-07-12/di-facts.jsonl"

def pc(v,c,e): return {"value":v,"conf":round(c,2),"evidence":e}
def dc(v,c,e): return {"value":v,"conf":round(c,2),"evidence":e}
def ctrl(ail,cent,c): return {"ailments":ail,"centrality":cent,"conf":round(c,2)}
def defs(layers,prim,c): return {"layers":layers,"primary":prim,"conf":round(c,2)}
def econ(rv,model,mt,bs,pt,c): return {"resource_verbatim":rv,"model":model,"meter_type":mt,"builder_source":bs,"plain_text":pt,"conf":round(c,2)}
def elem(lv,dm,c): return {"label_verbatim":lv,"damage_mode":dm,"conf":round(c,2)}
def mov(verbs,pol,is_mv,c): return {"verbs":verbs,"policy_while_casting":pol,"skill_is_movement":is_mv,"conf":round(c,2)}
def pfx(av,ac,ae,rv,rc,re,tv,tc,te,ampv,ampc,ampe,pxv,pxc,pxe,cv,cc,ce):
    return {
        "attr":pc(av,ac,ae),"range":pc(rv,rc,re),"tempo":pc(tv,tc,te),
        "amp":pc(ampv,ampc,ampe),"proxy":pc(pxv,pxc,pxe),"commitment":pc(cv,cc,ce)
    }

records = []

# ─────────────────────────────────────────────────────────────────────────────
# LAUNCH ERA (di-launch-2022) — high confidence 0.75-0.85
# ─────────────────────────────────────────────────────────────────────────────

# 1. di-monk-sss — Seven-Sided Strike Monk — DMHSSI
records.append({
    "kit_id":"di-monk-sss","folk_name":"Seven-Sided Strike Monk","game":"di","status":"positive",
    "atlas_key":"DMHSSI-KSMM-CD-PH-~~",
    "delivery":dc("at-target",0.82,"SSS teleports caster through 7 rapid sequential positions around a target, each delivering a melee blow — teleport delivery to each strike point"),
    "footprint":dc("multi-point",0.82,"Seven distinct strike positions scattered around/near the target area; not AoE from single origin"),
    "geo_text":"Seven-Sided Strike teleports the Monk through seven positions around the primary target, landing a blow at each point. Coverage is multi-point burst rather than a sustained sweep.",
    "control":ctrl(["stun"],"rider",0.72),
    "defense":defs(["dodge","resist"],"dodge",0.80),
    "economy":econ("Spirit","cooldown","n/a","n/a","Spirit generates from primary attacks; SSS is a secondary skill on a ~10-12s cooldown. DI Monk resource is simplified vs D3 — primary skills free, secondary on cooldown.",0.78),
    "element":elem("Physical","hit",0.78),
    "movement":mov(["teleport-strike"],"rooted",True,0.80),
    "prefix_claims":pfx(
        "DEX",0.82,"Monk is DEX/agility class; confirmed DEX attribute",
        "melee",0.80,"Seven-Sided Strike is melee range — strike positions clustered near target",
        "high",0.78,"Seven hits in rapid succession = very high tempo burst",
        "spiky",0.78,"Burst damage concentrated in ~1s window; classic spiky amp pattern",
        "solo",0.80,"Monk operates alone; no proxy entities spawned by SSS itself",
        "instant",0.82,"SSS activates instantly; teleport burst fires on cast"
    ),
    "mechanics_notes":"Core mechanic: 7-hit teleport burst. Each hit independent, allowing proc effects per strike. In DI PVP it serves as a reliable kill-combo opener. Rank 1 upgrade: additional hit or reduced CD — unverified exact wording.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI launch class mechanics; Seven-Sided Strike confirmed launch skill)"]
})

# 2. di-cyclone-monk-pvp — Cyclone CC Monk — DMMFSI
records.append({
    "kit_id":"di-cyclone-monk-pvp","folk_name":"Cyclone CC Monk","game":"di","status":"positive",
    "atlas_key":"DMMFSI-HSCM-CD-PH-~~",
    "delivery":dc("self-origin",0.82,"Cyclone Strike pulls enemies toward Monk and spins; damage originates from caster body"),
    "footprint":dc("small-radius",0.82,"AoE pull-and-spin in radius around caster; 5-6 yard estimated radius"),
    "geo_text":"Cyclone Strike creates a vortex centered on the Monk, pulling all nearby enemies inward and dealing damage. Radius is compact; functions as a point-gatherer plus burst.",
    "control":ctrl(["knockback","pull"],"core",0.80),
    "defense":defs(["dodge","resist"],"dodge",0.80),
    "economy":econ("Spirit","cooldown","n/a","n/a","Spirit generated by primary skills; Cyclone Strike on cooldown (~8s). In DI's simplified economy, secondary skills don't spend resource — they're cooldown gated.",0.78),
    "element":elem("Physical","hit",0.78),
    "movement":mov(["standard-move"],"walk",False,0.75),
    "prefix_claims":pfx(
        "DEX",0.82,"Monk = DEX class confirmed",
        "melee",0.80,"Cyclone Strike is close-range centered on caster",
        "med",0.75,"Spin lasts ~1-1.5s; not pure instant but not extended channel",
        "flat",0.72,"Consistent pull+damage; not burst-spiked amp pattern",
        "solo",0.80,"Caster-centric skill; no proxy units",
        "instant",0.78,"Cyclone activates immediately on cast; pull effect fires instantly"
    ),
    "mechanics_notes":"Primarily PVP CC tool in DI — pull + knockback combo disrupts enemy formations. In PVE less dominant than SSS. Control centrality = CORE (the CC is the point of this kit archetype, not the damage).",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Monk Cyclone Strike launch mechanics)"]
})

# 3. di-multishot-dh — Multishot Demon Hunter — DRHFSI
records.append({
    "kit_id":"di-multishot-dh","folk_name":"Multishot Demon Hunter","game":"di","status":"positive",
    "atlas_key":"DRHFSI-HMDG-SP-PH-~~",
    "delivery":dc("projectile",0.85,"Multishot fires a volley of arrows in a wide forward spread; classic projectile delivery"),
    "footprint":dc("cone",0.85,"Arrow spray covers wide forward cone; all targets in arc receive hits"),
    "geo_text":"Multishot releases a fan of arrows in a wide forward cone, hitting all enemies within the spread. High hit count per cast; effectively a cone-AoE through projectile density.",
    "control":ctrl(["slow"],"rider",0.65),
    "defense":defs(["dodge","resist"],"dodge",0.80),
    "economy":econ("Hatred","spend","n/a","n/a","In DI Hatred is simplified — Multishot functions as a high-Hatred-cost secondary skill. Primary skill (Crossbow Shot) generates Hatred freely. Effectively: spend model on a short cooldown.",0.75),
    "element":elem("Physical","hit",0.80),
    "movement":mov(["standard-move"],"rooted",False,0.78),
    "prefix_claims":pfx(
        "DEX",0.85,"DH is DEX class confirmed",
        "ranged",0.88,"Multishot is a ranged projectile skill; primary DH identity",
        "high",0.82,"Arrow volley fires instantly; high cadence in rotation",
        "flat",0.75,"Flat multi-target damage; amp doesn't vary sharply per hit",
        "solo",0.82,"No proxy units spawned; solo ranged DPS kit",
        "instant",0.82,"Multishot fires immediately on activation"
    ),
    "mechanics_notes":"Core DH damage output skill. In DI the DH leans on Multishot as the primary AoE clear tool. Pairs with Rain of Vengeance (cooldown zone denial) for sustained coverage. G2 note: wide fan = cone footprint, NOT a line.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Demon Hunter Multishot launch mechanics)"]
})

# 4. di-vengeance-strafe-dh — Strafe Weave DH — DRHFSI
records.append({
    "kit_id":"di-vengeance-strafe-dh","folk_name":"Strafe Weave DH","game":"di","status":"positive",
    "atlas_key":"DRHFSI-KMDD-SP-PH-~~",
    "delivery":dc("projectile",0.82,"Strafe fires arrows continuously while the DH moves; projectile delivery in movement direction"),
    "footprint":dc("cone",0.75,"Strafe channels a directional spray of arrows; footprint is a forward cone that reorients with movement"),
    "geo_text":"Strafe channels a continuous barrage of arrows while allowing movement, spraying a directional cone that follows the DH's facing. Vengeance activates as a steroid layer over the same delivery pattern.",
    "control":ctrl([],"none",0.72),
    "defense":defs(["dodge","resist"],"dodge",0.80),
    "economy":econ("Hatred","cooldown","n/a","n/a","Vengeance is a separate cooldown ultimate that empowers damage. Strafe is the sustained primary channel. In DI, this weave uses a Cooldown+channel hybrid economy.",0.72),
    "element":elem("Physical","hit",0.78),
    "movement":mov(["mobile-channel"],"full-move",False,0.80),
    "prefix_claims":pfx(
        "DEX",0.85,"DH = DEX confirmed",
        "ranged",0.88,"Strafe is ranged channel; clear ranged identity",
        "high",0.78,"Continuous fire rate; high tempo sustained channel",
        "flat",0.72,"Steady damage stream; no burst spikes in base Strafe",
        "solo",0.80,"No proxy; solo sustained output",
        "instant",0.78,"Strafe activates instantly; Vengeance CD pops instantly"
    ),
    "mechanics_notes":"Distinctive from Multishot by movement-while-firing mechanic. The 'weave' label in folk_name captures Vengeance (off-cooldown buff) layered over Strafe (mobile channel). Tempo = high via mobile channel; the sustained firing makes this different from Multishot's instant-volley pattern.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI DH Strafe + Vengeance mechanics)"]
})

# 5. di-ray-of-frost-wizard — Ray of Frost Wizard — IDHFSC (commit=C=channel)
records.append({
    "kit_id":"di-ray-of-frost-wizard","folk_name":"Ray of Frost Wizard","game":"di","status":"positive",
    "atlas_key":"IDHFSC-RNMG-SP-CO-~~",
    "delivery":dc("beam",0.88,"Ray of Frost fires a sustained cold beam from the caster to target; textbook beam delivery"),
    "footprint":dc("lane",0.85,"Narrow beam lane from caster to target point; hits everything in a thin line"),
    "geo_text":"Ray of Frost channels a continuous cold beam that freezes and slows all enemies in the narrow lane it passes through. Requires channeling; damage accumulates while the beam is held on target.",
    "control":ctrl(["freeze","slow"],"core",0.85),
    "defense":defs(["resist","glass"],"glass",0.75),
    "economy":econ("Arcane Power","channel","n/a","n/a","Ray of Frost drains Arcane Power continuously while channeling; beam ends when AP is exhausted or manually released. Standard channel-drain economy.",0.82),
    "element":elem("Cold","hit",0.88),
    "movement":mov(["none"],"rooted",False,0.85),
    "prefix_claims":pfx(
        "INT",0.88,"Wizard = INT class confirmed; cold spell",
        "mid",0.78,"Beam reaches to medium range from caster; not point-blank, not max range",
        "high",0.80,"Sustained high-frequency ticks while channeling",
        "flat",0.75,"Even damage ticks per frame; flat amp pattern",
        "solo",0.82,"Solo beam; no proxy entities",
        "channel",0.90,"Atlas key C confirmed; Ray of Frost is the quintessential channel skill"
    ),
    "mechanics_notes":"D1 (shield-split): RoF Wizard relies on dodge/kiting + glass defense. Not a shield/barrier kit. Control centrality = CORE (freeze is the purpose, not just a rider). G2: RoF is a TRUE BEAM — continuous sustained beam, not projectile chain. Flag for G2.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Wizard Ray of Frost; confirmed channel + freeze mechanic)"]
})

# 6. di-corpse-explosion-necro — Corpse Explosion Necromancer — IDHSSI
records.append({
    "kit_id":"di-corpse-explosion-necro","folk_name":"Corpse Explosion Necromancer","game":"di","status":"positive",
    "atlas_key":"IDHSSI-MSDM-AM-PH-~~",
    "delivery":dc("at-target",0.85,"Corpse Explosion detonates a corpse at target location; delivery is at-target detonation point"),
    "footprint":dc("small-radius",0.85,"Explosion radius around each detonated corpse; 3-4 yard radius per corpse burst"),
    "geo_text":"Corpse Explosion targets a nearby corpse and detonates it in a small AoE burst. Multiple corpses can be chained for overlapping explosions. Damage scales with corpse proximity to enemies.",
    "control":ctrl([],"none",0.72),
    "defense":defs(["shield-absorb","resist"],"shield-absorb",0.75),
    "economy":econ("Essence","ammo","n/a","corpse_availability","Corpse Explosion consumes a nearby corpse as ammo. Economy gated by corpse availability (enemy deaths or Bone Spirit spawning corpses). Essence spend per cast secondary constraint.",0.80),
    "element":elem("Physical","hit",0.78),
    "movement":mov(["standard-move"],"rooted",False,0.78),
    "prefix_claims":pfx(
        "INT",0.85,"Necromancer = INT class confirmed",
        "mid",0.78,"Corpse Explosion detonates at corpse location; mid-range targeting",
        "high",0.80,"High damage burst per explosion; can chain rapidly if corpses available",
        "spiky",0.80,"Damage very spiky — burst on corpse detonation, nothing in between",
        "solo",0.80,"No proxy minions; solo explosive delivery",
        "instant",0.82,"CE fires instantly on cast; detonation is immediate"
    ),
    "mechanics_notes":"Econ model = 'ammo' with corpses as the consumable. This is one of the few ammo-style economies in the corpus. Chain-CE can output enormous burst if many corpses available. In DI this is also a valid PVE clear strategy via corpse spawning skills.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Necro Corpse Explosion launch mechanics)"]
})

# 7. di-bone-wall-necro-pvp — Bone Wall Disruption Necro — IDMFSI
records.append({
    "kit_id":"di-bone-wall-necro-pvp","folk_name":"Bone Wall Disruption Necro","game":"di","status":"positive",
    "atlas_key":"IDMFSI-HLCM-CD-SH-~~",
    "delivery":dc("at-target",0.85,"Bone Wall is placed at target location; wall segments emerge from the ground at the targeted zone"),
    "footprint":dc("lane",0.85,"Bone Wall creates a blocking lane/barrier across the targeted area; functions as terrain obstacle"),
    "geo_text":"Bone Wall erupts at the target location as a horizontal barrier that blocks enemy movement. In PVP, used to split enemy formation or trap players. The wall persists for several seconds.",
    "control":ctrl(["immobilize"],"core",0.82),
    "defense":defs(["shield-absorb","resist"],"shield-absorb",0.78),
    "economy":econ("Essence","spend","n/a","n/a","Essence spend on cast. Bone Wall is a secondary skill on moderate cooldown. Economy: spend + cooldown dual gate.",0.78),
    "element":elem("Physical","hit",0.72),
    "movement":mov(["standard-move"],"rooted",False,0.78),
    "prefix_claims":pfx(
        "INT",0.85,"Necromancer = INT class",
        "mid",0.78,"Wall placed at mid-range from caster",
        "med",0.75,"Medium tempo — placement is instant but utility plays out over wall duration",
        "flat",0.72,"Wall does flat impact damage on formation; no burst spike",
        "solo",0.80,"No proxy minions in this kit archetype",
        "instant",0.82,"Wall emerges instantly on cast"
    ),
    "mechanics_notes":"D1: shield-absorb = Bone Armor (necro signature defense), not a physical shield. G2: Bone Wall footprint = lane (blocking barrier), NOT projectile delivery. C2: The control IS the purpose but this is a disruption PVP kit, not a pure-support kit. Control centrality = CORE.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Necro Bone Wall PVP mechanics)"]
})

# 8. di-minion-necro — Minion Necromancer — IRMFHI (proxy=H=heavy)
records.append({
    "kit_id":"di-minion-necro","folk_name":"Minion Necromancer","game":"di","status":"positive",
    "atlas_key":"IRMFHI-MNMM-SU-SH-~~",
    "delivery":dc("self-origin",0.82,"Minion commands/auras emanate from the Necromancer; minions execute attacks independently at range"),
    "footprint":dc("large-zone",0.82,"Minion swarm covers a large area around and ahead of the Necro; effective zone = summon spread radius"),
    "geo_text":"Summoned skeletons and golems spread across the combat area, attacking enemies throughout the zone. The Necromancer commands via aura and summon skills; minions deliver the damage at range.",
    "control":ctrl(["taunt"],"rider",0.60),
    "defense":defs(["shield-absorb","hp-stack"],"shield-absorb",0.78),
    "economy":econ("Essence","reserve","n/a","n/a","Minions have an upkeep cost in DI (simplified reserve model); some summons are permanent until death. Essence spend to re-summon fallen minions. Sustained passive reserve rather than active pool management.",0.75),
    "element":elem("Physical","hit",0.75),
    "movement":mov(["standard-move"],"full-move",False,0.80),
    "prefix_claims":pfx(
        "INT",0.85,"Necromancer = INT class",
        "ranged",0.82,"Minions operate at full range; Necro maintains safe distance",
        "med",0.75,"Sustained medium tempo; minions attack continuously but not burst",
        "flat",0.75,"Flat sustained DPS via minion attacks",
        "heavy",0.85,"Heavy proxy — all damage routed through minion entities; Necro itself does minimal direct damage",
        "instant",0.78,"Summon commands fire instantly; minions persist after"
    ),
    "mechanics_notes":"D1: Bone Armor (shield-absorb) is the primary defense layer on top of HP-stack; not a melee-dodge kit. Heavy proxy = the defining feature — Necro is the commander, minions are the damage delivery system. In DI the minion roster includes Skeleton Warriors, Skeleton Mages, and a Golem.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Necro summoner mechanics; Skeleton+Golem confirmed launch)"]
})

# 9. di-whirlwind-barb — Whirlwind Barbarian — SMHFSC (commit=C=channel, range=M=melee)
records.append({
    "kit_id":"di-whirlwind-barb","folk_name":"Whirlwind Barbarian","game":"di","status":"positive",
    "atlas_key":"SMHFSC-KSDT-CD-PH-~~",
    "delivery":dc("self-origin",0.88,"Whirlwind radiates outward from the spinning Barb body; classic self-origin rotational delivery"),
    "footprint":dc("small-radius",0.88,"Spin radius hits everything within ~3-4 yards of the Barb while channeling"),
    "geo_text":"Barbarian spins continuously, dealing damage to all enemies within melee range. Can move while spinning. Damage ticks at high frequency per revolution.",
    "control":ctrl(["knockback"],"rider",0.65),
    "defense":defs(["armor","hp-stack"],"armor",0.82),
    "economy":econ("Fury","channel","n/a","n/a","Fury drains while channeling Whirlwind; Fury generated by primary skills (Lacerate). Whirlwind ends when Fury is empty or manually released. Standard channel-drain economy.",0.82),
    "element":elem("Physical","hit",0.82),
    "movement":mov(["mobile-channel"],"full-move",False,0.85),
    "prefix_claims":pfx(
        "STR",0.88,"Barbarian = STR class confirmed",
        "melee",0.88,"Whirlwind hits melee range only; requires proximity",
        "high",0.82,"Continuous high-tick rate while channeling; very high tempo",
        "flat",0.78,"Even per-tick damage; no burst spikes",
        "solo",0.82,"Self-spun AoE; no proxy entities",
        "channel",0.90,"Atlas key C confirmed; WW is the archetype channel skill in DI Barb"
    ),
    "mechanics_notes":"Mobile channel archetype — distinctive for full-move policy while channeling. In DI this is the signature Barb clear skill. Fury drain rate limits duration. Pairs with Wrath of the Berserker (cooldown steroid).",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Barbarian Whirlwind; confirmed mobile channel + Fury drain)"]
})

# 10. di-frenzy-barb — Frenzy Barbarian — SMHFSI
records.append({
    "kit_id":"di-frenzy-barb","folk_name":"Frenzy Barbarian","game":"di","status":"positive",
    "atlas_key":"SMHFSI-HNDM-SP-PH-~~",
    "delivery":dc("at-target",0.85,"Frenzy delivers rapid sequential melee strikes at a single target; at-target delivery"),
    "footprint":dc("point",0.85,"Single-target melee strikes; point footprint (small splash possible at high stacks)"),
    "geo_text":"Frenzy stacks attack speed per hit, building toward a Frenzy-state where each strike is extremely fast. Each hit is a discrete melee blow on the primary target.",
    "control":ctrl([],"none",0.72),
    "defense":defs(["armor","hp-stack"],"armor",0.82),
    "economy":econ("Fury","spend","n/a","n/a","Frenzy-state is maintained by continued hitting; Fury generated per hit. Primary skill usage — effectively a sustained spend model that regenerates from its own attacks.",0.78),
    "element":elem("Physical","hit",0.82),
    "movement":mov(["standard-move"],"full-move",False,0.78),
    "prefix_claims":pfx(
        "STR",0.88,"Barbarian = STR class confirmed",
        "melee",0.88,"Frenzy is single-target melee; requires adjacent target",
        "high",0.85,"Attack speed stacking = extreme tempo at full Frenzy stacks",
        "flat",0.75,"Flat per-hit damage; amp comes from speed not per-hit spikes",
        "solo",0.82,"Solo melee striker; no proxy",
        "instant",0.82,"Each Frenzy hit fires instantly; no wind-up between strikes"
    ),
    "mechanics_notes":"Stack-based tempo escalation — Frenzy's core mechanic is attack speed increase per stack (up to 5). Peak Frenzy = highest tempo in DI Barb kit. Single-target focus distinguishes from Whirlwind AoE. Useful in DI for boss kill after clearing with WW.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Barbarian Frenzy mechanics; confirmed stack-based tempo)"]
})

# 11. di-hota-wotb-barb — HotA Burst Barbarian — SMMSSI (amp=spiky)
records.append({
    "kit_id":"di-hota-wotb-barb","folk_name":"HotA Burst Barbarian","game":"di","status":"positive",
    "atlas_key":"SMMSSI-MSMT-CD-PH-~~",
    "delivery":dc("at-target",0.85,"Hammer of the Ancients slams down at the target location; at-target impact"),
    "footprint":dc("small-radius",0.82,"HotA impact creates a small ground-slam AoE at target point"),
    "geo_text":"Hammer of the Ancients calls down a massive hammer at the targeted area, dealing very high burst damage in a small radius. Wrath of the Berserker activates as a cooldown steroid that amplifies the next HotA strikes.",
    "control":ctrl(["stun"],"rider",0.68),
    "defense":defs(["armor","hp-stack"],"armor",0.82),
    "economy":econ("Fury","spend","n/a","n/a","HotA costs Fury per cast; WotB is a separate cooldown ultimate. The kit weaves HotA spend with WotB timing for burst windows. Economy = spend (HotA) + cooldown (WotB).",0.78),
    "element":elem("Physical","hit",0.82),
    "movement":mov(["standard-move"],"rooted",False,0.78),
    "prefix_claims":pfx(
        "STR",0.88,"Barbarian = STR class",
        "melee",0.85,"HotA targets melee-range area around Barb",
        "med",0.75,"Not sustained high tempo like WW; burst windows around WotB cooldown",
        "spiky",0.82,"WotB windows create extreme damage spikes; atlas_key S confirmed amp=spiky",
        "solo",0.82,"Solo Barb kit; no proxy",
        "instant",0.82,"HotA slams instantly on activation"
    ),
    "mechanics_notes":"Burst archetype via WotB cooldown layering. Amp=spiky correctly characterizes the WotB burst window pattern. In DI this is both a PVE boss-burst and PVP burst-kill archetype.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Barb HotA + WotB mechanics; confirmed burst archetype)"]
})

# 12. di-crusader-banner-support — Banner Support Crusader — SMMFSI
# C2 SWEEP: closest to pure support in DI corpus; party-context PVP role
records.append({
    "kit_id":"di-crusader-banner-support","folk_name":"Banner Support Crusader","game":"di","status":"positive",
    "atlas_key":"SMMFSI-HLMT-SP-HO-~~",
    "delivery":dc("at-target",0.80,"Crusader throws/places a banner at target location; delivery = banner placement"),
    "footprint":dc("large-zone",0.80,"Banner radiates a buff aura over a large area around placement point; friendly units in range receive benefits"),
    "geo_text":"Crusader plants a Battle Standard (or equivalent) at the target location. The banner emits a persistent aura that buffs allied damage or defense for all friendly targets within the zone.",
    "control":ctrl([],"none",0.72),
    "defense":defs(["block","armor"],"block",0.80),
    "economy":econ("Wrath","cooldown","n/a","n/a","Banner placed on cooldown; Wrath generated by primary Crusader skills. In DI Crusader simplified: banner is a secondary cooldown skill that costs minimal Wrath.",0.75),
    "element":elem("Holy","hit",0.72),
    "movement":mov(["standard-move"],"walk",False,0.75),
    "prefix_claims":pfx(
        "STR",0.85,"Crusader = STR class confirmed",
        "melee",0.78,"Crusader operates at melee range; banner thrown to nearby position",
        "med",0.72,"Moderate tempo; kit is about sustained buff presence not burst",
        "flat",0.72,"Flat buff output; consistent support amp",
        "solo",0.70,"Atlas key S=solo; even support kit, the crusader's proxy is the banner itself (solo actor), not a minion army",
        "instant",0.78,"Banner placement fires instantly"
    ),
    "mechanics_notes":"C2 SWEEP: This is the DI corpus' closest pure-support candidate. However: DI Banner Support is specifically a Cycle of Strife (clan PVP) role — not a solo-context kit. In solo play, the Crusader uses damage skills; banner is secondary. C2 finding for DI: NO solo-context pure-support kit. Banner = party-PVP context only. D1: Crusader has BLOCK defense (physical shield), distinct from dodge/armor. Flag for D1 shield-split.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Crusader banner; Cycle of Strife support mechanics)"]
})

# 13. di-draw-quarter-crusader — Draw and Quarter Horse Crusader — SMMFSI
records.append({
    "kit_id":"di-draw-quarter-crusader","folk_name":"Draw and Quarter Horse Crusader","game":"di","status":"positive",
    "atlas_key":"SMMFSI-KSMM-CD-HO-~~",
    "delivery":dc("self-origin",0.85,"Draw and Quarter mounts the Crusader on a horse that charges; delivery = self-moving body"),
    "footprint":dc("lane",0.82,"Horse charge traces a lane through enemies; drags/knocks them along the charge path"),
    "geo_text":"Draw and Quarter mounts the Crusader on a spectral horse that charges forward in a straight lane, dragging enemies caught in its path. Direction is player-controlled. Effective for repositioning + CC sweep.",
    "control":ctrl(["knockback","drag"],"core",0.82),
    "defense":defs(["block","armor"],"armor",0.78),
    "economy":econ("Wrath","cooldown","n/a","n/a","Draw and Quarter is a secondary skill on a ~12-15s cooldown; Wrath cost minimal. Economy = cooldown gated.",0.75),
    "element":elem("Holy","hit",0.72),
    "movement":mov(["charge"],"full-move",True,0.88),
    "prefix_claims":pfx(
        "STR",0.85,"Crusader = STR",
        "melee",0.80,"Horse charge is melee-range interaction (dragging enemies along charge path)",
        "med",0.75,"Charge duration 1-2s; moderate tempo window",
        "flat",0.72,"Flat drag/push damage; control is the value not damage spike",
        "solo",0.80,"Solo actor charging through; no proxy entities",
        "instant",0.82,"Charge initiates instantly on cast"
    ),
    "mechanics_notes":"skill_is_movement=True: Draw and Quarter IS a movement skill — the horse charge IS repositioning. G2: lane footprint as horse charge traces a line through the field — flag as lane geometry not projectile. D1: Crusader has block (shield defense).",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Crusader Draw and Quarter horse charge mechanics)"]
})

# 14. di-blood-knight — Blood Knight (vampiric hybrid) — SDHFSI (range=D=mid, bk-2023)
records.append({
    "kit_id":"di-blood-knight","folk_name":"Blood Knight Vampiric Hybrid","game":"di","status":"positive",
    "atlas_key":"SDHFSI-HSMM-LC-SH-~~",
    "delivery":dc("at-target",0.72,"Blood Knight delivers melee/mid-range vampiric strikes and blood abilities at target; at-target delivery"),
    "footprint":dc("small-radius",0.68,"Blood abilities detonate in small AoE bursts around targets"),
    "geo_text":"Blood Knight uses vampiric lance strikes and blood detonations in a mid-to-close range. Darkness Realm form enables alternate delivery of shadow/blood abilities.",
    "control":ctrl(["fear","slow"],"rider",0.62),
    "defense":defs(["sustain-leech","shield-absorb"],"sustain-leech",0.72),
    "economy":econ("Blood (class resource)","meter","n/a","blood_orb_collection","Blood Knight collects Blood Orbs from defeated enemies to power ultimate abilities. Secondary skills on cooldown. Unique meter economy gated by blood orb availability.",0.68),
    "element":elem("Shadow","hybrid",0.70),
    "movement":mov(["dash","standard-move"],"full-move",False,0.70),
    "prefix_claims":pfx(
        "STR",0.78,"Blood Knight is STR-based class",
        "mid",0.70,"Blood Knight engages at mid/close range; lance reach mid-range",
        "high",0.68,"High tempo attacks in vampiric mode",
        "flat",0.65,"Flat sustained vampiric output; blood detonations add spiky element",
        "solo",0.70,"Solo fighter; vampiric abilities self-targeted",
        "instant",0.72,"Strike skills fire instantly"
    ),
    "mechanics_notes":"Added in 2023 Blood Knight patch. Conf moderated (bk-2023 era; partial training data). Economy = unique blood orb collection meter — captures distinctly as 'meter' with builder_source=blood_orb_collection. D1: sustain-leech is the PRIMARY defense (vampiric HP recovery is the defining defensive layer). Shadow element flag.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Blood Knight 2023 class mechanics; vampiric design confirmed)"]
})

# ─────────────────────────────────────────────────────────────────────────────
# TEMPEST (di-tempest-2024) — moderate confidence 0.60-0.70
# ─────────────────────────────────────────────────────────────────────────────

# 15. di-tempest — Tempest (Mist Touched clones) — DDHFLI (range=D=mid, proxy=L=light)
records.append({
    "kit_id":"di-tempest","folk_name":"Tempest Mist Clones","game":"di","status":"positive",
    "atlas_key":"DDHFLI-KSDD-SU-PH-~~",
    "delivery":dc("self-origin",0.62,"Tempest class creates Mist Touched clones that split from the caster and attack; delivery from caster-origin"),
    "footprint":dc("multi-point",0.58,"Clones disperse to multiple nearby positions and attack independently; multi-point coverage"),
    "geo_text":"Tempest creates ethereal Mist Touched clones that split off and attack nearby enemies with lightning abilities. Clones chain lightning between targets in proximity.",
    "control":ctrl(["slow","shock"],"rider",0.55),
    "defense":defs(["dodge","resist"],"dodge",0.60),
    "economy":econ("Spirit (Tempest)","cooldown","n/a","n/a","Tempest skills on individual cooldowns; clone summon on moderate CD. Primary skill generates Spirit freely.",0.55),
    "element":elem("Lightning","hit",0.62),
    "movement":mov(["standard-move"],"full-move",False,0.58),
    "prefix_claims":pfx(
        "DEX",0.65,"Tempest class is agility-oriented; DEX class confirmed per class design",
        "mid",0.60,"Clones engage at medium range from caster; lightning chains nearby",
        "high",0.60,"Clone attacks fire at high frequency in aggregate",
        "flat",0.55,"Flat lightning DPS via clones; amp uncertain",
        "light",0.60,"Clones = light proxy (not a heavy minion army; temporary mirror images)",
        "instant",0.62,"Clone summon activates instantly"
    ),
    "mechanics_notes":"2024 class addition; conf reduced (partial training data for 2024 DI content). Mist Touched clone mechanic: temporary mirror images that deal lightning damage. proxy=light (L) distinguishes from minion-heavy builds — clones are momentary copies not persistent summons. di-5.0-2026 changes post-cutoff.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Tempest class 2024; partial training data — clone + lightning archetype confirmed)"]
})

# ─────────────────────────────────────────────────────────────────────────────
# DRUID (di-druid-2025) — lower confidence 0.55-0.65
# ─────────────────────────────────────────────────────────────────────────────

# 16. di-druid-bear — Bear Druid (heal-shift) — SMMFLI (proxy=L=light)
records.append({
    "kit_id":"di-druid-bear","folk_name":"Bear Druid Heal-Shift","game":"di","status":"positive",
    "atlas_key":"SMMFLI-MSMT-LC-PH-~~",
    "delivery":dc("self-origin",0.60,"Bear form attacks originate from the transformed Druid body; self-origin melee"),
    "footprint":dc("small-radius",0.58,"Bear swipes and ground slams in close proximity to caster"),
    "geo_text":"Druid shifts into Bear Form to deliver powerful melee strikes and ground slams in close range. The 'heal-shift' label suggests cycling between forms to recover HP between engagements.",
    "control":ctrl(["slow","taunt"],"rider",0.50),
    "defense":defs(["armor","hp-stack"],"armor",0.60),
    "economy":econ("Spirit (Druid)","cooldown","n/a","n/a","DI Druid uses form-shift skills on cooldown; Bear Form is a sustained mode not a per-cast skill. Economy likely cooldown-gated transformation.",0.52),
    "element":elem("Physical","hit",0.60),
    "movement":mov(["standard-move"],"full-move",False,0.55),
    "prefix_claims":pfx(
        "STR",0.62,"Druid Bear Form is STR/physical class archetype",
        "melee",0.65,"Bear attacks are melee-range",
        "med",0.55,"Moderate tempo in bear form; not burst, not channel",
        "flat",0.52,"Steady melee output; amp uncertain",
        "light",0.55,"Light proxy — Druid may summon small spirits but Bear Form itself is solo",
        "instant",0.55,"Form shift and attacks fire instantly"
    ),
    "mechanics_notes":"2025 class addition; conf significantly reduced. 'Heal-shift' note in folk_name suggests Druid cycles forms to exploit HP recovery in a non-bear form. Defense layer includes heal component (sustain-leech?). di-2026-era changes post-cutoff. Knowledge is partial.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Druid class 2025; partial training data — Bear Form + shapeshifter confirmed at class level)"]
})

# ─────────────────────────────────────────────────────────────────────────────
# METEOR WIZARD (di-2024-2026-era) — moderate conf; base mechanics pre-cutoff
# ─────────────────────────────────────────────────────────────────────────────

# 17. di-meteor-wizard — Meteor/Stealth Wizard — IRMSSW (commit=W=wind-up)
records.append({
    "kit_id":"di-meteor-wizard","folk_name":"Meteor Stealth Wizard","game":"di","status":"positive",
    "atlas_key":"IRMSSW-HLMD-CD-FI-~~",
    "delivery":dc("at-target",0.78,"Meteor calls a fireball to fall on the target location after a wind-up delay; at-target impact"),
    "footprint":dc("large-zone",0.75,"Meteor impact creates a large fire AoE at target; pool of fire persists briefly"),
    "geo_text":"Meteor channels a brief wind-up then calls a massive meteor strike at the target location, dealing high burst damage in a large AoE. A fire pool persists at impact for additional DoT.",
    "control":ctrl(["slow"],"rider",0.65),
    "defense":defs(["glass","resist"],"glass",0.72),
    "economy":econ("Arcane Power","cooldown","n/a","n/a","Meteor is a high-cost Arcane Power secondary skill on moderate cooldown. Stealth component (from item/class feature) allows preemptive positioning. Economy = spend + cooldown.",0.72),
    "element":elem("Fire","hybrid",0.78),
    "movement":mov(["none"],"rooted",False,0.72),
    "prefix_claims":pfx(
        "INT",0.85,"Wizard = INT class",
        "ranged",0.82,"Meteor targets at max range; long-range impact",
        "med",0.75,"Rotation tempo — Meteor on cooldown limits cadence; med tempo",
        "spiky",0.80,"Meteor is the burst spike; atlas_key S=spiky confirmed",
        "solo",0.80,"Solo caster; no proxy",
        "wind-up",0.82,"Atlas key W confirmed; Meteor has a cast/travel delay before impact"
    ),
    "mechanics_notes":"Commit=wind-up is significant: the target can react to the incoming Meteor (DI pvp counterplay). Fire pool = hybrid damage (hit on impact + DoT pool). 'Stealth' in folk_name = Wizard uses Teleport/invisibility to preposition before Meteor cast. 2026 changes unknown.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Wizard Meteor; wind-up impact + fire pool confirmed; stealth pre-positioning strategy known)"]
})

# ─────────────────────────────────────────────────────────────────────────────
# POST-CUTOFF: 3 kits (conf ≤ 0.50)
# ─────────────────────────────────────────────────────────────────────────────

post_cutoff_kits = [
    {
        "kit_id":"di-warlock-launch","folk_name":"Warlock (launch state)","game":"di","status":"positive",
        "atlas_key":"IRMSLI-_SM_-SP-SH-~~",
        "delivery":dc("at-target",0.40,"Warlock class added in DI 5.0 (2026); delivery pattern presumed ranged/shadow at-target from atlas key INT-ranged prefix — post-cutoff, low conf"),
        "footprint":dc("small-radius",0.38,"Warlock likely has AoE shadow abilities; exact footprint unknown — post-cutoff abstain"),
        "geo_text":"Warlock (DI 5.0, 2026) — post-cutoff class. Shadow/demonic themed ranged caster per atlas key. Precise geometry not known.",
        "control":ctrl(["unknown"],"rider",0.35),
        "defense":defs(["shield-absorb","glass"],"shield-absorb",0.38),
        "economy":econ("Shadow (Warlock)","cooldown","n/a","n/a","Warlock resource economy post-cutoff; DI pattern suggests cooldown-based secondary skills with class resource. Abstain on specifics.",0.38),
        "element":elem("Shadow","hit",0.42),
        "movement":mov(["standard-move"],"full-move",False,0.38),
        "prefix_claims":pfx(
            "INT",0.48,"Atlas key I=INT; Warlock likely INT caster class — preserved from atlas",
            "ranged",0.48,"Atlas key R=ranged; Warlock ranged caster presumed",
            "med",0.40,"Atlas key M=med tempo — preserved claim, low conf",
            "spiky",0.40,"Atlas key S=spiky — preserved claim",
            "light",0.40,"Atlas key L=light proxy — preserved",
            "instant",0.40,"Atlas key I=instant — preserved"
        ),
        "mechanics_notes":"POST-CUTOFF: DI 5.0 (2026) class. Only era = di-5.0-2026. All conf capped at ≤0.50 per post-cutoff law. Prefix claims preserved from atlas key as provenance; source-verified conf not achievable.",
        "era_confirmed":True,"post_cutoff":True,"dossier_owed":True,
        "rank1_upgrade":False,
        "sources_used":["kb (DI Warlock class name + class theme; no mechanic detail — post-cutoff)"]
    },
    {
        "kit_id":"di-bombardment-wizard-pvp","folk_name":"Bombardment Artillery Wizard","game":"di","status":"positive",
        "atlas_key":"IRMSSI-MLDG-CD-FI-~~",
        "delivery":dc("at-target",0.42,"Bombardment delivers projectile/area strikes at target location; at-target presumed from 'artillery' folk_name"),
        "footprint":dc("large-zone",0.40,"Artillery bombardment likely covers large AoE zone — post-cutoff, low conf"),
        "geo_text":"Bombardment Artillery Wizard (di-2026-era) — post-cutoff archetype. Large-zone fire-based bombardment at range per atlas key and folk_name. Precise mechanics unknown.",
        "control":ctrl(["slow"],"rider",0.35),
        "defense":defs(["glass","resist"],"glass",0.40),
        "economy":econ("Arcane Power","cooldown","n/a","n/a","Wizard bombardment on cooldown economy; DI 2026 changes unknown.",0.38),
        "element":elem("Fire","hit",0.44),
        "movement":mov(["none"],"rooted",False,0.40),
        "prefix_claims":pfx(
            "INT",0.48,"Atlas key I=INT; Wizard confirmed",
            "ranged",0.48,"Atlas key R=ranged; artillery = long range confirmed",
            "med",0.40,"Atlas key M; preserved",
            "spiky",0.40,"Atlas key S=spiky; burst damage burst presumed",
            "solo",0.42,"Atlas key S=solo; no proxy",
            "instant",0.40,"Atlas key I=instant; preserved"
        ),
        "mechanics_notes":"POST-CUTOFF: di-2026-era only. Conf capped ≤0.50. PVP-specific artillery archetype. All claims from atlas key provenance only.",
        "era_confirmed":True,"post_cutoff":True,"dossier_owed":True,
        "rank1_upgrade":False,
        "sources_used":["kb (DI Wizard archetype recognized; 2026 bombardment build post-cutoff)"]
    },
    {
        "kit_id":"di-spiritform-druid-pvp","folk_name":"Spirit-Form Druid (complaint-tier)","game":"di","status":"positive",
        "atlas_key":"SDMFSI-HSMM-CD-PH-~~",
        "delivery":dc("self-origin",0.40,"Spirit form likely creates self-origin spirit emanation; post-cutoff abstain on delivery"),
        "footprint":dc("small-radius",0.38,"Spirit form likely has close-range AoE presence; post-cutoff low conf"),
        "geo_text":"Spirit-Form Druid (di-2026-era) — post-cutoff PVP archetype. Complaint-tier label in folk_name suggests overpowered PVP viability. Spirit form mechanics unknown.",
        "control":ctrl(["unknown"],"core",0.35),
        "defense":defs(["armor","hp-stack"],"armor",0.40),
        "economy":econ("Spirit (Druid)","cooldown","n/a","n/a","Druid 2026 spirit-form economy unknown; cooldown presumed from DI patterns.",0.35),
        "element":elem("Physical","hit",0.42),
        "movement":mov(["standard-move"],"full-move",False,0.40),
        "prefix_claims":pfx(
            "STR",0.48,"Atlas key S=STR; Druid STR confirmed",
            "mid",0.40,"Atlas key D=mid; preserved",
            "med",0.40,"Atlas key M=med; preserved",
            "flat",0.40,"Atlas key F=flat; preserved",
            "solo",0.42,"Atlas key S=solo; Druid solo confirmed",
            "instant",0.40,"Atlas key I=instant; preserved"
        ),
        "mechanics_notes":"POST-CUTOFF: di-2026-era only. Conf capped ≤0.50. 'Complaint-tier' = PVP overpowered at time of corpus capture. Spirit form = alternate Druid state (not Bear Form). All claims atlas-provenance only.",
        "era_confirmed":True,"post_cutoff":True,"dossier_owed":True,
        "rank1_upgrade":False,
        "sources_used":["kb (DI Druid class confirmed; spirit-form variant post-cutoff)"]
    },
]
records.extend(post_cutoff_kits)

# ─────────────────────────────────────────────────────────────────────────────
# META-SYSTEM RECORDS: di-essence-transfer, di-resonance-awakening, di-inferno-ladder
# Delivery = other (these are progression/economy systems, not combat skills)
# ─────────────────────────────────────────────────────────────────────────────

records.append({
    "kit_id":"di-essence-transfer","folk_name":"Legendary Essence System","game":"di","status":"positive",
    "atlas_key":"______-____-SP-__-~~",
    "delivery":dc("other",0.88,"Legendary Essence is a crafting/transfer system not a combat skill; delivery=other is correct classification"),
    "footprint":dc("other",0.88,"System-level mechanic; no spatial footprint applies"),
    "geo_text":"Legendary Essence Transfer allows players to extract the legendary power from one item and apply it to another, enabling build customization without item replacement. A crafting economy record.",
    "control":ctrl([],"none",0.88),
    "defense":defs([],"other",0.75),
    "economy":econ("Legendary Crests/Gold","recipe","n/a","n/a","Legendary Essence extraction costs Legendary Crests (premium currency) and Gold. Recipe-economy: consume crafting materials to transfer legendary affix between items. Primary economy system for DI build crafting.",0.82),
    "element":elem("n/a","hit",0.88),
    "movement":mov([],"rooted",False,0.88),
    "prefix_claims":pfx(
        "n/a",0.0,"Atlas key blank; prefix undefined for system record",
        "n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a"
    ),
    "mechanics_notes":"SYSTEM RECORD: Legendary Essence Transfer is DI's primary item-crafting economy mechanic. Allows build identity to persist across item upgrades. Economy model = recipe (destroy source item's power, stamp onto target). This is a genre-canon economy record documenting DI's build-investment system.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Legendary Essence system; crafting economy confirmed at launch)"]
})

records.append({
    "kit_id":"di-resonance-awakening","folk_name":"Resonance/Awakening Spend-as-Stat","game":"di","status":"positive",
    "atlas_key":"______-____-SP-__-~~",
    "delivery":dc("other",0.85,"Resonance is a progression/stat-investment system; no combat delivery"),
    "footprint":dc("other",0.85,"System-level; no spatial footprint"),
    "geo_text":"Resonance represents DI's endgame stat-investment progression. Players invest resources (often premium) into Resonance levels that permanently increase character power. Awakening is the class-advancement layer that unlocks skill upgrades.",
    "control":ctrl([],"none",0.85),
    "defense":defs([],"other",0.75),
    "economy":econ("Awakening Dust/Resonance Materials","harvest","n/a","n/a","Resonance progression consumes materials harvested from endgame activities. Players invest permanently — harvest-into-stat economy with gacha-tier monetization. Awakening unlocks via completing specific challenges.",0.78),
    "element":elem("n/a","hit",0.85),
    "movement":mov([],"rooted",False,0.85),
    "prefix_claims":pfx(
        "n/a",0.0,"Blank atlas key","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a"
    ),
    "mechanics_notes":"SYSTEM RECORD: DI's endgame progression economy. 'Spend-as-stat' is accurate — Resonance materials are consumed to permanently raise stats. Genre-canon significance: DI introduced mobile ARPG gacha-progression loops that influenced subsequent mobile ARPGs. Economy model=harvest captures the material-gathering → investment flow.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Resonance + Awakening endgame systems; confirmed at launch + updated versions)"]
})

records.append({
    "kit_id":"di-inferno-ladder","folk_name":"Inferno/Paragon Ladder Numeric Spine","game":"di","status":"positive",
    "atlas_key":"______-____-SP-__-~~",
    "delivery":dc("other",0.85,"Paragon/Inferno ladder is a numeric progression system; no combat delivery"),
    "footprint":dc("other",0.85,"System-level; no spatial footprint"),
    "geo_text":"DI's Inferno difficulty system and Paragon-equivalent ladder (Challenge Rift + Paragon trees) provide a perpetual numeric power spine. Players push through increasing difficulty tiers to advance.",
    "control":ctrl([],"none",0.85),
    "defense":defs([],"other",0.75),
    "economy":econ("XP/Challenge Rift Clear","spend","n/a","n/a","Paragon points spent to activate stat-increasing nodes in a talent tree (simplified vs D3). Inferno ladder = ascending Challenge Rift difficulty. Economy: XP spend into Paragon tree; Inferno difficulty = gated by Paragon thresholds.",0.78),
    "element":elem("n/a","hit",0.85),
    "movement":mov([],"rooted",False,0.85),
    "prefix_claims":pfx(
        "n/a",0.0,"Blank atlas key","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a","n/a",0.0,"n/a"
    ),
    "mechanics_notes":"SYSTEM RECORD: DI's numeric power spine. DI replaced D3-style unlimited Paragon with a tree-based system gated by Challenge Rift progression. Genre-canon record documenting the mobile ARPG numeric spine model that differs fundamentally from PC ARPG endgames.",
    "era_confirmed":True,"post_cutoff":False,"dossier_owed":False,
    "rank1_upgrade":False,
    "sources_used":["kb (DI Challenge Rift + Paragon system; mobile ARPG progression spine confirmed at launch)"]
})

# ─────────────────────────────────────────────────────────────────────────────
# WRITE OUTPUT
# ─────────────────────────────────────────────────────────────────────────────

pos = sum(1 for r in records if r.get("status")=="positive" and not r.get("post_cutoff"))
pc_count = sum(1 for r in records if r.get("post_cutoff"))
neg = sum(1 for r in records if r.get("status")=="negative")
total = len(records)

print(f"DI: {total} records | pos={pos} neg={neg} post-cutoff={pc_count}")

with open(OUT, "w") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Written: {OUT}")
print()
print("=== DIRECTED SWEEP RESULTS (DI) ===")
print("C2 (support-existence): CLOSEST = di-crusader-banner-support (Cycle of Strife PVP support role)")
print("  However: Banner Support is party-PVP context ONLY, not solo-context.")
print("  C2 finding for DI: NO solo-context pure-support kit.")
print("G2 (line-vs-projectile):")
print("  TRUE BEAM: di-ray-of-frost-wizard (sustained cold beam, delivery=beam, footprint=lane)")
print("  LANE footprint (not beam): di-bone-wall-necro-pvp (blocking wall = lane), di-draw-quarter-crusader (horse charge = lane)")
print("  Chains in DI: none; DI lightning (Tempest) = clone-based multi-point, not chain-hop")
print("D1 (shield-split):")
print("  BLOCK (physical shield): di-crusader-banner-support, di-draw-quarter-crusader")
print("  SHIELD-ABSORB (Bone Armor): di-bone-wall-necro-pvp, di-minion-necro, di-corpse-explosion-necro")
print("  SUSTAIN-LEECH (vampiric): di-blood-knight")
print("  ARMOR/HP-stack: all Barb kits (whirlwind, frenzy, hota-wotb), di-druid-bear")
print("  DODGE: all DH kits (multishot, strafe), Monk kits (sss, cyclone), di-tempest")
print("  GLASS: di-ray-of-frost-wizard, di-meteor-wizard")
