# R-C9-98: the battle mage's character slot, DERIVED from so_d7/scene_pkg/character_sorceress.json (read-only): same body,
# clips, layers and casts; new gear_dir, gear stacks, armed rule and morph rule. Regenerate, don't edit.
#   python3 s26_make_pkg.py
import json, os, copy
C9 = '/Users/admin/Games/reincarnated-collaboration/astra_test_01/burst/runs/C-9'
S = C9 + '/gear_sets/sorceress_battlemage'
src = json.load(open(C9 + '/so_d7/scene_pkg/character_sorceress.json'))
ch = copy.deepcopy(src)
# v2 ORDER: the hood goes on WITH the breastplate. All pieces were cut from ONE dressed shell, so nothing lies under the
# hood's shoulder cape: a breastplate without the hood showed bare shift on top of her shoulders (stills v1, stack 2).
STACKS = [[], ["gown", "legs"], ["gown", "legs", "breastplate", "hood"], ["gown", "legs", "breastplate", "hood", "gauntlets"],
          ["gown", "legs", "breastplate", "hood", "gauntlets", "wand", "grimoire"]]
NAMES = ["base", "+gown+legs (body armour, pants)", "+breastplate+hood (chest piece, helm)", "+gauntlets", "full kit (+wand +grimoire)"]
ch.update({
    "_note": ("THE BATTLE-MAGE SET for the sorceress (Matt R-C9-98: steel plate battle mage, the scarlet hood, wand and "
              "grimoire). GENERATED by gear_sets/sorceress_battlemage/scripts/s26_make_pkg.py from so_d7's character slot: the "
              "same body (so_d7/export/so-body.glb, NOT re-exported), clips, casts and carry layers. Only the gear changes."),
    "gear_dir": "res://models/sorceress_battlemage",
    "gear_manifest": "res://data/gear_manifest_sorceress_battlemage.json",
    "gear_stacks": STACKS,
    "gear_stack_names": NAMES,
    "armed_when_pieces": ["wand"],
    "morph_rules": {"grip_R": "wand", "under_battlemage": "gown"},
    "model": "res://models/sorceress_battlemage/so-body_battlemage.glb",
    "_model_note": ("her body with ONE added morph, under_battlemage (scripts/s28_body_morph.py, a binary glTF patch of so_d7/export/so-body.glb: clips byte-identical), which draws the linen shift in under the armour while the gown is worn"),
    "_morph_note": ("grip_R closes her right fist with the WAND. The GAUNTLETS carry their own grip_R and grip_L (the body's "
                    "keys transferred vertex by vertex), so the scene must set the key on every worn mesh that has it, not on "
                    "the body only -- otherwise the bare fist closes inside an open steel glove and pokes through it."),
    "_carry_note": ("arm_layer_armed_R / upper_armed / strike_release are the STAFF's carry, inherited unchanged: the wand is "
                    "mounted on weapon_r at the staff's own mount (its axis along the staff's, its grip where the staff's axis "
                    "passes the fist), so the same carry holds it. Tuning a lighter wand carry is a later step."),
})
for k in ("gear_stack_detail", "_gear_stacks_note"):
    ch.pop(k, None)
os.makedirs(S + '/scene_pkg', exist_ok=True)
json.dump(ch, open(S + '/scene_pkg/character_sorceress_battlemage.json', 'w'), indent=1)
man = json.load(open(S + '/export_v7/assemble.json'))
gm = {"_note": "the battle mage's gear pieces: each a skinned GLB on her 26 joints (gear.gd binds each under the body's Skeleton3D)",
      "pieces": {k: dict(file=k + ".glb", **{kk: vv for kk, vv in v.items() if kk in ("mode", "bone", "offset_m", "hem_overlap_m", "keys", "length_m", "height_m", "carry")})
                 for k, v in man["pieces"].items()},
      "layer_order": ["body", "gown", "legs", "breastplate", "hood", "gauntlets", "wand", "grimoire"]}
json.dump(gm, open(S + '/scene_pkg/gear_manifest_sorceress_battlemage.json', 'w'), indent=1)
print("wrote", S + '/scene_pkg/character_sorceress_battlemage.json', "and the gear manifest")
