# THE SORCERESS'S SCENE PACKAGE (conductor insert, 2026-09-30: Matt asked where she is on his phone; the integration
# drax makes her playable on the painted Barrow phone page as ?c=sorceress). Every number is READ from the file that
# owns it -- her export manifest, the JOIN-1 kit's sockets, the pack index's measured height -- never typed, so a
# re-export is followed by re-running this, not by editing JSON.
#
#   python3 scene_pkg/make_pkg.py        (from so_d7/)  ->  scene_pkg/character_sorceress.json
#                                                           scene_pkg/gear_manifest_sorceress.json
#                                                           scene_pkg/sockets_sorceress.json
#
# SHAPES: character_sorceress.json is cliffside3d/godot/data/character.json's shape (knight.gd reads it and nothing
# else about the occupant); gear_manifest_sorceress.json is data/gear_manifest.json's (gear.gd binds its `pieces`;
# knight.gd reads its `locomotion_in_place` for the walk and run speeds). Neither scene file is edited here.
import hashlib, json, os
HERE = os.path.dirname(os.path.abspath(__file__)); D7 = os.path.dirname(HERE); C9 = os.path.dirname(D7)
J = lambda *p: json.load(open(os.path.join(*p)))
sha = lambda p: hashlib.sha256(open(p, 'rb').read()).hexdigest()
man_p = os.path.join(D7, "export", "manifest.json"); man = J(man_p)
# v2 (2026-09-30): her clips on their sources' own keys -- the kit and the pack index are v2's (v1's pack, declared, sits in
# join1_pack/d2-fire-sorc and is not read here: the height and sockets are the same, the clips are not)
kit = J(C9, "join1_render", "kits", "d2-fire-sorc_v2.json")
idx = J(C9, "join1_pack_draft", "d2-fire-sorc_v2", "matrix_index.json")
scene_char = J(C9, "cliffside3d", "godot", "data", "character.json")          # READ ONLY: the shape and his scale constants
scene_gear = J(C9, "cliffside3d", "godot", "data", "gear_manifest.json")      # READ ONLY
PPM = 100.617553710938                                                        # knight.gd / gear.gd PPM (canvas px per metre)
cl = man["staff_hold"]["carry_layer"]
loco = man["locomotion_in_place"]
casts = man["casts"]
H = float(idx["source"]["h_model_m"])
FACTOR = float(scene_gear["world_scale_rule"]["factor"])
PIECES = ["robe", "mantle", "belt", "bracers", "circlet", "staff"]
files = {p: os.path.join(D7, "export", p + ".glb") for p in PIECES}
body = os.path.join(D7, "export", "so-body.glb")

# ---------------------------------------------------------------- gear manifest (gear.gd's shape)
gp = man["gear"]["pieces"]
pieces = []
for p in PIECES:
    g = gp.get(p, {})
    e = dict(piece=p, mode=g.get("mode", "skin"), glb=p + ".glb", sha256=sha(files[p]))
    if g.get("bones"): e["bones"] = g["bones"]
    if g.get("bone"): e["bones"] = [g["bone"]]
    if g.get("offset_m") is not None: e["offset_m"] = g["offset_m"]
    pieces.append(e)
gear = dict(
    _note="THE SORCERESS'S GEAR MANIFEST, in the shape of cliffside3d/godot/data/gear_manifest.json: gear.gd binds every `pieces` "
          "entry as a skinned mesh on her body's Skeleton3D (each file carries her 26 joints, identical in name and order), and "
          "knight.gd reads `locomotion_in_place` for her walk and run speeds. GENERATED by so_d7/scene_pkg/make_pkg.py from her "
          "export manifest (sha %s) -- re-run it after any re-export; do not hand-edit a speed here." % sha(man_p)[:12],
    body="so-body.glb", body_sha256=sha(body), height_m=H, scale_applied=1.0,
    facing="-Y (Blender) = +Z in Godot/glTF", his_right="-X", up="+Z (Blender) = +Y in Godot/glTF",
    body_shape_keys=["grip_R", "grip_L"], layer_order=["body", "robe", "belt", "mantle", "bracers", "circlet", "staff"],
    world_scale_rule=dict(factor=FACTOR, world_height_m=round(H * FACTOR, 5),
                          _note="HIS world factor applied to her, as the scene does: she renders at her own 1.6995 m times the "
                                "same factor, i.e. %.3f m against his %.3f m" % (H * FACTOR, scene_gear["world_scale_rule"]["world_height_m"])),
    pieces=pieces,
    shape_key_rules=dict(grip_R="1 while the staff is equipped -- closes the right fist round the shaft (%s)" % cl.get("clip", ""),
                         grip_L="0 always: the off hand is free (the Fire Ball hand)"),
    locomotion_in_place=dict(rule=loco.get("rule"),
                             walk={k: loco["walk"][k] for k in ("seconds", "speed_m_s", "planted_intervals")},
                             run={k: loco["run"][k] for k in ("seconds", "speed_m_s", "planted_intervals")},
                             _source="so_d7/export/manifest.json locomotion_in_place (seconds, speed_m_s, planted_intervals); "
                                     "its recut records carry the history"),
)

# ---------------------------------------------------------------- character entry (character.json's shape)
full, arm, chest_arm = cl["filter_bones_full"], cl["filter_bones_arm"], cl["filter_bones_chest_arm"]
char = dict(
    _note="THE CHARACTER SLOT for the sorceress, in the shape of cliffside3d/godot/data/character.json (knight.gd reads it and nothing "
          "else about the occupant). GENERATED by so_d7/scene_pkg/make_pkg.py. `clips` / `clips_armed` map the scene's ROLES to her "
          "clip names: idle/walk/run the locomotion, the two STRIKE slots carry her two casts -- attack (the slash key) = Fire Ball, "
          "chop = Meteor. hit and death have NO role in knight.gd today: see `roles_knight_lacks` and scene_pkg/README.md.",
    model="res://models/sorceress/so-body.glb", model_height_m=H, forward_axis=[0.0, 0.0, 1.0],
    clips=dict(idle="idle", walk="walk", run="run", attack="cast_fireball"),
    clips_armed=dict(idle="idle", walk="walk", run="run", attack="cast_fireball", chop="cast_meteor"),
    roles_knight_lacks=dict(hit="hit", death="death",
                            _note="her clips for the two states knight.gd has no role for; the scene needs a one-shot per state "
                                  "(death holding its last frame) fired by the MODEL's hit-recovery and death events"),
    armed_when_pieces=["staff"], loop=["idle", "walk", "run"],
    gear_manifest="res://data/gear_manifest_sorceress.json", gear_dir="res://models/sorceress",
    gear_stacks=[[], ["robe", "mantle", "belt", "bracers", "circlet"], PIECES], gear_stack_names=["base", "costume", "full kit"],
    morph_rules=dict(grip_R="staff"),
    # THE STAFF LAYERS, in knight.gd's own terms
    arm_layer_armed_R=dict(action=cl["clip"], bones=full, weight=1.0,
                           _note="THE STAFF CARRY over idle, walk and run: knight.gd's right-arm guard slot (blend_r, a filtered "
                                 "Blend2 over LOCOMOTION ONLY, below the strikes) filtered to the carry's NINE bones -- Spine02, "
                                 "Spine01, Spine, neck, Head and the staff arm -- at weight 1 (%s). No action_block: she has no block."
                                 % man["staff_hold"]["carry_layer"]["how"][:60]),
    upper_armed=dict(walk=cl["clip"], run=cl["clip"], bones=[b for b in full if b not in arm],
                     _note="THE CARRY'S SPINE, held through knight.gd's ARMED UPPER slot -- NOT because this is an armed gait but "
                           "because it is the one slot whose filter paths come from the LOCOMOTION clips' tracks (_apply_upper). "
                           "The carry keeps Spine01, Spine, neck and Head at REST, and Godot's glTF import drops rest-valued "
                           "tracks: staff_carry_R arrives with 8 tracks for its 9 bones (Spine02, the shoulder and the arm), so "
                           "arm_layer_armed_R -- whose filter comes from the ACTION's own tracks -- cannot hold the upper spine, "
                           "and the run's spine carried the staff to 32 deg (designed 13.4). With this slot the walk and run "
                           "match the reference staff_layer.gd EXACTLY (0.000 deg); the idle keeps the idle clip's own spine sway "
                           "(knight.gd's upper chain plays the idle ROLE clip in idle): 5.8 deg off the reference, tilt 12.0 "
                           "against 10.8. scene_pkg/test/, measured."),
    arm_layer_armed=dict(action=cl["clip"], bones=[],
                         _note="knight.gd's _build_anim_tree RETURNS EARLY -- no tree at all -- unless this left-arm layer's action "
                               "exists. Her left arm carries nothing, so the action is the carry clip with an EMPTY filter: the "
                               "`blend` node then passes locomotion through untouched."),
    strike_release=dict(pose=cl["clip"], bones=arm, guard_throughout=["cast_fireball"], at_s={}, over_s=0.08,
                        _note="THE FIRE BALL'S ARM-ONLY CARRY: knight.gd's recovery release (rel_<key>, a filtered Blend2 INSIDE "
                              "each strike's one-shot) held at 1 for the whole strike (`guard_throughout`), filtered to the four "
                              "staff-arm bones, on the carry pose -- the staff stays carried while her LEFT hand throws. The Meteor "
                              "is in neither list, so it owns every bone: its staff motion is baked into its own weapon_r tracks."),
    casts={"cast_fireball": dict(slot="attack", release_s=casts["cast_fireball"]["release_s"], socket="cast_hand"),
           "cast_meteor": dict(slot="chop", release_s=casts["cast_meteor"]["release_s"], socket="cast_hand_meteor"),
           "_note": "RELEASE per cast (from her export manifest's casts.<clip>.release_s): the instant the spell leaves the hand, clip "
                    "time. knight.gd has no release event today (strike_release.at_s is the recovery release, a different thing): "
                    "the placeholder VFX needs one, firing when the strike's position crosses release_s."},
    speed_measured_at_scale=scene_char["speed_measured_at_scale"],
    walk_px_s=round(loco["walk"]["speed_m_s"] * PPM, 1), run_px_s=round(loco["run"]["speed_m_s"] * PPM, 1),
    _speed_note="FALLBACKS ONLY: knight.gd reads the live speeds from the gear manifest's locomotion_in_place by CLIP name (walk "
                "%.3f m/s, run %.3f m/s, her FOOT-LOCK speeds by the scene's stance rule at the clips' own keys) x PPM %.3f = canvas px/s at the reference "
                "scale, rescaled by figure_scale / speed_measured_at_scale -- the same convention as his, since the scene applies "
                "his world factor to her. walk %.4f s and run %.4f s are one cycle each (re-cut on their sources' own keys)."
                % (loco["walk"]["speed_m_s"], loco["run"]["speed_m_s"], PPM, loco["walk"]["seconds"], loco["run"]["seconds"]),
    scale_steps=scene_char["scale_steps"], scale_default_lit=scene_char["scale_default_lit"],
    scale_default_painted=scene_char["scale_default_painted"], transitions=scene_char["transitions"],
    _copied_from_his="scale_steps, scale_default_*, speed_measured_at_scale and transitions are HIS (the scene's own constants), "
                     "copied so the slot is complete; nothing else of his applies to her",
    foot_lock=False,
    layers_knight_lacks=dict(
        hit=dict(want="chest_arm: %s at the carry pose, weight 1, throughout the hit" % ", ".join(chest_arm),
                 lacks="(1) a hit ROLE and one-shot; (2) PER-STRIKE release bones -- strike_release.bones is ONE list for every "
                       "strike, and the Fire Ball needs the 4 arm bones while hit needs Spine02 + those 4"),
        death=dict(want="none: she falls with the staff (conductor, 2026-09-30)", lacks="a death ROLE and a one-shot that HOLDS its last frame"),
        cast_meteor=dict(want="none", lacks="nothing: a strike owns every bone"),
        cast_fireball=dict(want="arm-only carry", lacks="nothing: strike_release with guard_throughout"),
        idle_walk_run=dict(want="the 9-bone carry (spine at rest + the staff arm)",
                           lacks="filter paths from the LAYERED-OVER clips: arm_layer_armed_R filters on the action's own tracks, "
                                 "and the import drops the carry's rest-valued spine tracks -- worked around in DATA with upper_armed "
                                 "(walk/run exact; idle keeps its own spine sway, 5.8 deg off the reference)")),
)

# ---------------------------------------------------------------- sockets (placeholder VFX)
ks = kit["sockets"]
sockets = dict(
    _note="Her sockets for the placeholder VFX, as BONE + OFFSET: point = bone world origin + the bone's +Y axis (normalized) x "
          "along_bone_m x the live figure scale. None is a marker node in the GLBs (gear.gd carries markers across; these are data). "
          "Same definitions as the JOIN-1 sprite pack's sockets_m (join1_render/kits/d2-fire-sorc.json).",
    cast_hand=dict(bone=ks["cast_hand"]["bone"], along_bone_m=ks["cast_hand"]["along_bone_m"],
                   what="the LEFT palm (wrist + 0.07 m along the hand): the Fire Ball's spawn point, and every state's but the Meteor's"),
    cast_hand_meteor=dict(bone=ks["cast_hand"]["per_state_bone"]["cast_meteor"], along_bone_m=ks["cast_hand"]["along_bone_m"],
                          what="the RIGHT palm: the Meteor's call hand"),
    main_tip=dict(bone=ks["main_tip"]["bone"], along_bone_m=ks["main_tip"]["along_bone_m"],
                  what="the staff's crown: weapon_r + 0.8765 m along its +Y (the Meteor's baked slide moves weapon_r, and the tip with it)"),
    main_grip=dict(bone=ks["main_grip"]["bone"], along_bone_m=0.0, what="the staff grip: the weapon_r joint"),
)
for name, obj in (("character_sorceress.json", char), ("gear_manifest_sorceress.json", gear), ("sockets_sorceress.json", sockets)):
    json.dump(obj, open(os.path.join(HERE, name), "w"), indent=1)
    print("wrote scene_pkg/%s" % name)
print("height %.4f m (world %.4f at x%.5f); walk %.3f m/s -> %.1f px/s, run %.3f m/s -> %.1f px/s at the reference scale; release %s / %s"
      % (H, H * FACTOR, FACTOR, loco["walk"]["speed_m_s"], char["walk_px_s"], loco["run"]["speed_m_s"], char["run_px_s"],
         casts["cast_fireball"]["release_s"], casts["cast_meteor"]["release_s"]))
