-- corpus_kf4_acceptance_asserts.sql
-- KIT-FIDELITY KF-4 — mechanical acceptance asserts (canon record → compiled fighter).
-- Author: gamora (sim seam). Generated by reincarnated.simulation.kit_compiler.emit_assert_sql.
-- Math note: src/reincarnated/simulation/math/kf4-kit-compiler-2026-07-23.md.
-- IDEMPOTENT + byte-rebuildable: DELETE prior KF-4 rows (by '[KF-4-compiled]' marker) then re-INSERT.
-- Additive: touches ONLY kit_acceptance_assert + mechanic_gap_docket for the pilots.
-- last_result = evaluation of the assert against the COMPILED FIGHTER (KF-4 exit).
BEGIN TRANSACTION;

-- (1) idempotent cleanup — prior KF-4 rows only (KF-1 record-asserts untouched)
DELETE FROM kit_acceptance_assert
 WHERE kit_id IN ('d2-firewall-sorc', 'd2-fire-sorc', 'poe1-cyclone', 'poe2-bonestorm', 'gd-flames-of-ignaffar-purifier')
   AND expected_state LIKE '%[KF-4-compiled]%';
DELETE FROM mechanic_gap_docket
 WHERE mechanism_class = 'poe1_cyclone_base_weapon_dps_build_point_gap'
   AND intake_lane = 'KF-4-compiler';

-- (2) docket for the cyclone base_weapon_dps GAP (red-test doctrine -> §5 fork)
INSERT INTO mechanic_gap_docket (mechanism_class, spec_text_or_path, evidence_kits, status, provenance_json, disposition, docket_family, source_kit_id, intake_lane)
VALUES ('poe1_cyclone_base_weapon_dps_build_point_gap', 'poe1 Cyclone per-hit base = weapon_DPS x 59% effectiveness x 3.0 attack-speed; weapon DPS at the 3.15 build point is un-anchored (context target 650, not a build-point anchor). kit_composition base_weapon_dps = gap_excluded. The compiled fighter renders dealt damage PARTIAL (pre-weapon-DPS); has_damage_base assert RED. This is a VALUE-harvest gap (source-game weapon-DPS build point), NOT an engine-mechanic gap — geometry/cadence/element compile fully GREEN. Reported for a charter §5 swap decision; the compiler does NOT swap or fabricate.', '["poe1-cyclone"]', 'open', '{"run":"KIT-FIDELITY","gate":"KF-4","author":"gamora","kind":"value_gap"}', 'reported_for_swap_decision — options: (A) harvest 3.15 build-point weapon DPS; (B) accept partial cyclone (shape faithful, magnitude gapped); (C) §5 swap to reserve. Conductor/Matt rules, not the compiler.', 'KF-4-value-gap', 'poe1-cyclone', 'KF-4-compiler');

-- (3) mechanical acceptance asserts (authored vs record, evaluated vs compiled fighter)
-- d2-firewall-sorc (held=False)
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'primary_delivery_class == ''zone''', 'record skill_geometry_band.delivery_class = ''zone'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'primary_geometry == ''line''', 'record geometry_value ''placed_lane'' → spatial ''line'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'primary_geometry_rich == ''placed_lane''', 'record mapping geometry_value = ''placed_lane'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'skill_count == 1', 'record kit_mapping.skills length = 1 [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'element == ''fire''', 'record canon_corpus.original_element = ''fire'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'primary_cadence == ''cooldown''', 'record skill_geometry_band.cadence_class = ''cooldown'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-firewall-sorc', 'primary_has_damage_base == True', 'a compiled fighter must carry an anchored base magnitude [KF-4-compiled]', 'green', NULL);

-- d2-fire-sorc (held=False)
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'primary_delivery_class == ''projectile''', 'record skill_geometry_band.delivery_class = ''projectile'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'primary_geometry == ''point''', 'record geometry_value ''single_target'' → spatial ''point'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'primary_geometry_rich == ''single_target''', 'record mapping geometry_value = ''single_target'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'skill_count == 2', 'record kit_mapping.skills length = 2 [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'element == ''fire''', 'record canon_corpus.original_element = ''fire'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'primary_cadence == ''spam''', 'record skill_geometry_band.cadence_class = ''spam'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'projectiles_per_cast == 1', 'record anchored count = 1 (count_per_cast) [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('d2-fire-sorc', 'primary_has_damage_base == True', 'a compiled fighter must carry an anchored base magnitude [KF-4-compiled]', 'green', NULL);

-- poe1-cyclone (held=False)
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'primary_delivery_class == ''motion''', 'record skill_geometry_band.delivery_class = ''motion'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'primary_geometry == ''circle''', 'record geometry_value ''whirlwind'' → spatial ''circle'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'primary_geometry_rich == ''whirlwind''', 'record mapping geometry_value = ''whirlwind'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'skill_count == 1', 'record kit_mapping.skills length = 1 [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'element == ''physical''', 'record canon_corpus.original_element = ''physical'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'primary_cadence == ''channel''', 'record skill_geometry_band.cadence_class = ''channel'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe1-cyclone', 'primary_has_damage_base == True', 'record: base_weapon_dps GAP-EXCLUDED (3.15 build-point weapon DPS un-anchored) [KF-4-compiled]', 'red', (SELECT docket_id FROM mechanic_gap_docket WHERE mechanism_class = 'poe1_cyclone_base_weapon_dps_build_point_gap' AND intake_lane = 'KF-4-compiler' LIMIT 1));

-- poe2-bonestorm (held=False)
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'primary_delivery_class == ''projectile''', 'record skill_geometry_band.delivery_class = ''projectile'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'primary_geometry == ''point''', 'record geometry_value ''multi_projectile'' → spatial ''point'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'primary_geometry_rich == ''multi_projectile''', 'record mapping geometry_value = ''multi_projectile'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'skill_count == 2', 'record kit_mapping.skills length = 2 [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'element == ''physical''', 'record canon_corpus.original_element = ''physical'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'primary_cadence == ''channel''', 'record skill_geometry_band.cadence_class = ''channel'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'projectiles_per_cast == 10', 'record anchored count = 10 (n_shards pin) [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('poe2-bonestorm', 'primary_has_damage_base == True', 'a compiled fighter must carry an anchored base magnitude [KF-4-compiled]', 'green', NULL);

-- gd-flames-of-ignaffar-purifier (held=True)
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'primary_delivery_class == ''zone''', 'record skill_geometry_band.delivery_class = ''zone'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'primary_geometry == ''cone''', 'record geometry_value ''cone'' → spatial ''cone'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'primary_geometry_rich == ''cone''', 'record mapping geometry_value = ''cone'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'skill_count == 2', 'record kit_mapping.skills length = 2 [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'element == ''fire''', 'record canon_corpus.original_element = ''fire'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'primary_cadence == ''channel''', 'record skill_geometry_band.cadence_class = ''channel'' [KF-4-compiled]', 'green', NULL);
INSERT INTO kit_acceptance_assert (kit_id, assert_text, expected_state, last_result, routed_docket_id)
VALUES ('gd-flames-of-ignaffar-purifier', 'primary_has_damage_base == True', 'record: FoI base-damage rank table GAP (R-K5, T4 pending) — HELD, untested until T4 [KF-4-compiled]', 'untested', NULL);

COMMIT;

-- SUMMARY: 35 GREEN · 1 RED · 1 GAP/untested across 4 pilots + 1 held.