#!/usr/bin/env python3
"""Post-export patch: binds the Eye-of-Reckoning WHIRLWIND VFX to the 2D pixel
"EoR Warlord" keeper in an already-exported Godot project.

MUST RUN AFTER attack_patch.py. This patch anchors on the exact blocks that
attack_patch.py inserts into scripts/keeper.gd, so "run attack_patch.py first"
is enforced mechanically rather than asked for in a comment.

Usage:
    python3 whirlwind_patch.py <path to exported godot dir>
    e.g. python3 whirlwind_patch.py runs/C-8/cliffside_v40-warlord3/godot

---------------------------------------------------------------------------
THE RIBBON RUNS ON A LEVEL BAND, NOT ON THE DRAWN MACE. Conductor correction,
Run C-8, after Matt spotted the mace height wandering.

The source's rule is "generated from the WEAPON'S ACTUAL POSITION", and the
first build of this patch took that literally: it read the per-frame mace-head
pixels out of vfx_fit.json and drove both the ribbon's bearing and its radius
from them. Measured, that is not a sweep. Across the eight attack stills the
mace head sits at

    0.180  0.184  0.238  0.594  0.674  0.891  0.912  0.962

of figure height above the sole -- a spread of 0.782 H against the reference
clip's own sweep band of [0.551, 0.746], spread 0.195. Four times the
reference's wander, and on three frames the head is level with or above the
helm. A ribbon threaded through those points is a scribble, not an ellipse.

So the HEIGHT comes from a constant band (SWEEP_BAND +/- SWEEP_WOBBLE, the 2D
form of the source's SWEEP_Y / SWEEP_WOBBLE plane), the ANGLE comes from the
animation frame by the cells' own declared construction (still k = 45 deg from
S), and the RADII stay as the conductor measured them. Where the ribbon and the
drawn mace disagree, the ribbon is right; the art is being regenerated onto
this band.

NOTHING BELOW READS A MACE ROW to drive anything. The only use left for
vfx_fit.json's per-frame mace data is `report_level_band_evidence`, which
prints the height spread that justified the band and is never consumed.
---------------------------------------------------------------------------

What it does:
  1. Validates the project is attack-patched (attack_* animations in
     frames/keeper.tres at exactly 0.400 s/loop, the attack input action, the
     attack_patch marker in keeper.gd).
  2. Reads runs/C-8/vfx_fit.json for the sprite registration it still trusts:
     canvas, figure height, sole row, body-centre X, R_TRAIL and R_ENGAGE.
  3. Derives, per direction, the PHASE ROLL of that direction's 8 frames
     against the canonical attack_S still order, BY HASH. (The C-8 cells are
     TURNAROUND-AS-SPIN: all eight facings are exact rotations of ONE eight-
     still revolution -- registration.json method R-C8-5/R-C8-4. This script
     re-derives the rotation from the bytes rather than trusting that note,
     and fails loudly if any direction is not a clean rotation.)
  4. Checks the level band against the 2D restatement of the source's
     disjoint-band inequality and fails loudly if it is violated.
  5. Writes <project>/whirlwind_fit.json (generated; regenerated byte-identical
     on every run) and <project>/scripts/whirlwind.gd (generated verbatim).
  6. Patches <project>/scripts/keeper.gd, marker-guarded, to build the effect
     in _ready() and to drive begin()/end() off the attack state transitions.

No .tscn is edited. The two draw layers are created in GDScript with explicit
z_index, which is also how the near/far split is enforced -- see whirlwind.gd.

Idempotent: whirlwind_fit.json and scripts/whirlwind.gd are regenerated from
scratch each run (byte-identical); the keeper.gd patch is marker-guarded.

Fails loudly: every validation runs before anything is written; any
inconsistency raises and exits non-zero with no partial write.
"""
import hashlib
import json
import math
import re
import sys
from pathlib import Path

DIRECTIONS = ('S', 'SW', 'W', 'NW', 'N', 'NE', 'E', 'SE')
SCRIPT_DIR = Path(__file__).resolve().parent
RUN_ROOT = SCRIPT_DIR.parent              # runs/C-8
CELLS_ROOT = RUN_ROOT / 'cells'
VFX_FIT = RUN_ROOT / 'vfx_fit.json'

# ===========================================================================
# THE CONSTANTS BLOCK. Everything the new character frames could move lives
# here, so they drop in without a code change.
# ===========================================================================

# ---------------------------------------------------------------------------
# THE SWEEP BAND. The 2D form of the source's SWEEP_Y = 1.20 m on H_STAND =
# 1.85 m (0.6486 of standing height) with SWEEP_WOBBLE = 0.08 m (+/- 0.0432 H).
# Set to 0.55 H on this chibi, where the proportions differ from the 3D rig's.
# ---------------------------------------------------------------------------
SWEEP_BAND = 0.55         # sweep-plane height above the sole, of figure height
SWEEP_WOBBLE = 0.04       # helical wobble amplitude, of figure height

# ---------------------------------------------------------------------------
# ⚑ THE DISJOINT-BAND INEQUALITY, RESTATED FOR 2D AND ASSERTED BELOW.
#
# The source turned "renders over the caster's lower body" into a number:
# trail band [1.02, 1.38] m against LOWER_BODY_TOP (hips) 0.9088 m -- disjoint
# by 0.111 m. The same discipline here, in figure-height units on this chibi:
# the sweep plane must sit ABOVE the hips and BELOW the chin. These two are the
# guard, and they are checked rather than admired.
# ---------------------------------------------------------------------------
LOWER_BODY_TOP = 0.35     # hips
HEAD_BOTTOM = 0.753       # chin / neck pinch

# ---------------------------------------------------------------------------
# ⚑ THE PHASE ANCHOR IS DECLARED, NOT FITTED, AND THAT IS A DELIBERATE CALL.
#
# The cells' own registration.json declares the construction: "phase assignment
# is BY CONSTRUCTION (index k = 45 deg from S), not independently verified",
# with the flag "angle spacing is eye-judged, not measured". Canonical still 0
# is the S-facing still, and S faces the camera -- screen-down -- which in this
# file's bearing convention (x right, y down) is +90 deg.
#
# I did try to fit this to the current art instead, using the mace X ONLY (the
# rows being the corrupted channel): the one-parameter least squares returns
# 184.2 deg with a residual RMS of 32 % of R_TRAIL. A 32 % residual on a
# one-parameter fit is not a phase measurement, it is a statement that these
# eight stills do not lie on a uniform sweep in X either. So the fit is
# REPORTED and NOT USED, and the declared construction stands.
#
# This is the one constant to move if the art wants the ribbon registered
# elsewhere. It is independent of the SIGN of the sweep, which is the separate
# (and separately evidenced) constant immediately below.
# ---------------------------------------------------------------------------
SWEEP_BEARING0_DEG = 90.0   # bearing of the sweep at canonical frame 0

# ---------------------------------------------------------------------------
# ⚑ THE SIGN OF THE SWEEP. GET THIS BACKWARDS AND THE RIBBON COUNTER-ROTATES
#   AGAINST THE CHARACTER, WHICH IS EXACTLY WHAT SHIPPED AND WHAT MATT CAUGHT.
#
# THE CONVENTION, STATED ONCE SO IT CANNOT BE RE-DERIVED WRONG. Bearings are
# screen-space with X RIGHT and Y DOWN, and a point on the sweep sits at
#
#       ( cos(theta) * R ,  sin(theta) * R * GROUND_SQUASH )
#
# Because Y is DOWN, sin(theta) > 0 is the BOTTOM of the screen -- the side
# NEAREST the camera. So walking theta upward goes
#
#       0 deg  RIGHT  ->  90 deg  BOTTOM  ->  180 deg  LEFT  ->  270 deg  TOP
#
# i.e. right -> down -> left -> up, which is CLOCKWISE to the viewer.
#
#       theta INCREASING  ==  CLOCKWISE on screen  ==  +360 per revolution
#       theta DECREASING  ==  ANTICLOCKWISE        ==  -360 per revolution
#
# ⚑ THIS VALUE HAS BEEN BOTH SIGNS, AND THE SECOND CHANGE WAS NOT A CORRECTION
#   OF THE FIRST. READ THIS BEFORE "FIXING" IT BACK.
#
# It shipped at -360, was changed to +360 on 2026-09-21 to match the warlord4
# art, and is -360 again on warlord5. Nothing about the convention above
# changed and no measurement was wrong: THE ART WAS DELIBERATELY REVERSED
# BETWEEN THE TWO BUILDS, and this constant simply follows it.
#
# MATT'S RULING, 2026-09-21, which is the reason and will outlive the builds:
# a RIGHT-HANDER turns COUNTER-CLOCKWISE. The forehand sweep starts on the
# right and crosses to the left, and the body keeps turning left; right-handed
# hammer and discus throwers rotate counter-clockwise seen from above. The
# warlord4 art turned clockwise, which is effectively a repeated BACKHAND.
#
# ⚑ AND THE FIX WAS FRAME REVERSAL, NOT MIRRORING, WHICH IS THE WHOLE POINT.
#   Reversing the 16-frame revolution flips the rotational sense and PRESERVES
#   handedness. Mirroring would have done the opposite -- fixed the sense and
#   swapped the hands -- which is a separate defect Matt is holding a decision
#   on. Two transforms, both of which "fix the spin", and only one of which is
#   correct: worth knowing which was used before reasoning about this file.
#
# VERIFIED ON warlord5's OWN BYTES rather than inferred from the note:
#   * The 16 frames are warlord4's frames at indices [0, 15, 14, ... 1] --
#     every step -1 mod 16, i.e. an exact reversal anchored at frame 0, with
#     the identical image set (hash-for-hash).
#   * SHIELD TEST, the same instrument run on warlord4 and independent of the
#     mace: the shield is widest when FACE-ON, and face-on to the camera is its
#     NEAREST point, theta = +90. Its horizontal centroid through that frame
#     runs +17 px -> +68 -> +115 off the body axis: moving RIGHT, at +98 px
#     across the pair -- the exact mirror of warlord4's -98. The tangent at
#     theta = 90 for DECREASING theta is (+1, 0) = RIGHT.
#     THETA DECREASING => COUNTER-CLOCKWISE => this constant is NEGATIVE.
#   * Per-direction roll, derived from the bytes: S=0 SW=14 W=12 NW=10 N=8
#     NE=6 E=4 SE=2, i.e. (-2k) mod 16 -- inverted from warlord4's +2k exactly
#     as a reversal requires.
#
# ⚑ A NOTE ON WHAT `sense_check()` CAN AND CANNOT TELL YOU. It compares the
#   drawn geometry against this constant, and both derive from this constant,
#   so it CANNOT detect a disagreement with the CHARACTER -- it will pass at
#   either sign. It catches a geometry/constant desync, nothing more. The only
#   thing that ties this file to the art is a measurement of the ART, like the
#   shield test above. Re-run that, not just the probe, whenever the art moves.
#
# ⚑ AN INSTRUMENT I BUILT AND THEN REJECTED, recorded so nobody rebuilds it:
#   tracking the mace head by its cool teal glint returned the opposite answer
#   on warlord4 with cross-product votes at 5 against 6, i.e. a coin flip. It
#   was catching the shield's green rim-light as often as the mace, and on one
#   frame placed the mace at the BOTTOM of the sweep when it is plainly
#   upper-left. A tracker that is wrong half the time averages to noise and
#   then reports the noise as a direction. The check ran; the check was not
#   the check.
# ---------------------------------------------------------------------------
SWEEP_REVOLUTION_DEG = -360.0

# ---------------------------------------------------------------------------
# GROUND_SQUASH -- the vertical foreshortening of a circle lying on the
# cliffside's ground plane. CARRIED from this project's own ground-plane
# primitives: every ground-lying VFX surface the exporter emits is drawn as
# `scale = Vector2(1, ground_squash)` on a circular texture (the G2 field disc,
# the G4 "orbit ellipse", the floor light, the impact decal). Across the 28
# instances shipped in a cliffside export the modal value is 0.60 (0.58 in the
# e3 family, 0.72 in one), and export/effect_kit.py validates the field into
# [0.50, 0.65]. The sweep circle is the same geometric object as G4's orbit
# ellipse, so it must sit on the same floor as the rest of the scene's effects.
#
# NOT the contact shadow's 0.08/0.22 = 0.364: those are two INDEPENDENT art
# constants in export/parallax_scene.py (footprint width 0.22*H, blob height
# 0.08*H), a deliberately flattened contact blob, not a projection.
#
# NOT measurable from the mace locus: a free 4-parameter ellipse fit to the 8
# measured mace heads returns 0.92, but the 8 samples leave 97 deg and 112 deg
# gaps that straddle BOTH minor-axis extremes -- the data cannot see the minor
# axis at all. Pinning the squash at 0.60 and refitting returns a semi-major
# axis of 185.79 px against the conductor's measured R_TRAIL of 186.97 px
# (0.6 % agreement), which is the corroboration this constant rests on.
# ---------------------------------------------------------------------------
GROUND_SQUASH = 0.60

# CARRIED from wwcr_whirlwind.gd: R_ENGAGE / R_TRAIL = 3.5150 / 2.3598.
ENGAGE_RATIO = 1.4895

LOOP_SECONDS = 0.40


def fail(msg):
    print('whirlwind_patch: FAIL: ' + msg, file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Step 1: the project must already be attack-patched
# ---------------------------------------------------------------------------

ANIMATION_BLOCK_RE = re.compile(
    r'\{"frames": \[(?P<frames>.*?)\], "loop": (?P<loop>true|false), '
    r'"name": &"(?P<name>[^"]+)", "speed": (?P<speed>[0-9.]+)\}', re.DOTALL)
FRAME_ID_RE = re.compile(r'ExtResource\("(\d+)"\)')
ATTACK_MARKER = '    # PATCH(drax attack_patch): attack state'


def require_attack_patched(project):
    tres = project / 'frames' / 'keeper.tres'
    if not tres.is_file():
        fail(f'expected SpriteFrames resource not found: {tres}')
    text = tres.read_text()
    found = {}
    for m in ANIMATION_BLOCK_RE.finditer(text):
        found[m.group('name')] = (len(FRAME_ID_RE.findall(m.group('frames'))),
                                  float(m.group('speed')), m.group('loop') == 'true')
    missing = [d for d in DIRECTIONS if f'attack_{d}' not in found]
    if missing:
        fail(f'frames/keeper.tres has no attack_{{{",".join(missing)}}} animations -- '
             f'run attack_patch.py against this project first')
    counts = {}
    for d in DIRECTIONS:
        n, fps, loop = found[f'attack_{d}']
        if not loop:
            fail(f'attack_{d} is not a looping animation -- refusing to phase-lock a '
                 f'ribbon to a one-shot')
        if abs(n / fps - LOOP_SECONDS) > 1e-6:
            fail(f'attack_{d}: n/speed = {n}/{fps} = {n / fps:.6f}s, expected exactly '
                 f'{LOOP_SECONDS}s -- the ribbon revolution is defined as one animation '
                 f'loop and cannot be phase-locked to a loop of another length')
        # ⚑ FRAME COUNT IS NOT CONSTRAINED, AND MUST NOT BE. The ribbon locks to
        # the loop's PHASE, not to a frame index: builds differ (the turnaround
        # is 8 @ 20 fps; the clip cut is 12 @ 30 and 9 @ 22.5 for N/NE/NW) and
        # they can even differ BETWEEN DIRECTIONS in the same build. All that
        # matters is the 0.400 s above, which is what makes the same effect drop
        # onto either build unchanged.
        counts[d] = n

    pg = project / 'project.godot'
    if not pg.is_file() or not re.search(r'^attack=', pg.read_text(), re.MULTILINE):
        fail('project.godot has no "attack=" input action -- run attack_patch.py first')

    keeper = project / 'scripts' / 'keeper.gd'
    if not keeper.is_file():
        fail(f'keeper.gd not found: {keeper}')
    if ATTACK_MARKER not in keeper.read_text():
        fail('scripts/keeper.gd does not carry the attack_patch marker -- run '
             'attack_patch.py against this project first')
    return counts


# ---------------------------------------------------------------------------
# Step 2: the sprite registration this patch still trusts
# ---------------------------------------------------------------------------

def load_fit():
    if not VFX_FIT.is_file():
        fail(f'conductor fit not found: {VFX_FIT}')
    try:
        fit = json.loads(VFX_FIT.read_text())
    except json.JSONDecodeError as exc:
        fail(f'{VFX_FIT}: not valid JSON: {exc}')
    for key in ('canvas', 'figure_height', 'body_centre', 'sole_row',
                'R_TRAIL_px', 'R_ENGAGE_px'):
        if key not in fit:
            fail(f'{VFX_FIT}: missing required key "{key}"')
    if fit['canvas'] != 512:
        fail(f'{VFX_FIT}: canvas is {fit["canvas"]}, expected 512')
    want = ENGAGE_RATIO * fit['R_TRAIL_px']
    if abs(fit['R_ENGAGE_px'] - want) > 0.5:
        fail(f'{VFX_FIT}: R_ENGAGE_px {fit["R_ENGAGE_px"]:.3f} is not the source\'s '
             f'R_ENGAGE/R_TRAIL = {ENGAGE_RATIO} ratio on R_TRAIL_px '
             f'({want:.3f}) -- refusing to silently redefine the footprint')
    return fit


def check_band(fit):
    """⚑ The disjoint-band inequality, as a check rather than an adjective."""
    lo = SWEEP_BAND - SWEEP_WOBBLE
    hi = SWEEP_BAND + SWEEP_WOBBLE
    if lo <= LOWER_BODY_TOP:
        fail(f'sweep band bottom {lo:.4f} H is not above the hips '
             f'({LOWER_BODY_TOP} H) -- this is the source\'s "must not render over '
             f'the caster\'s lower body" defect, and the guard exists to stop it')
    if hi >= HEAD_BOTTOM:
        fail(f'sweep band top {hi:.4f} H is not below the chin ({HEAD_BOTTOM} H) -- '
             f'a trail across the helm reads as a halo, not as a sweep')
    margin_lo = lo - LOWER_BODY_TOP
    margin_hi = HEAD_BOTTOM - hi
    H = fit['figure_height']
    return (lo, hi, margin_lo, margin_hi, margin_lo * H, margin_hi * H)


def report_level_band_evidence(fit):
    """The mace-head height spread that put the ribbon on a LEVEL BAND instead
    of on the drawn weapon. REPORTED, NEVER USED -- printed every run so the
    reason for the band is on screen rather than only in a comment.

    ⚑ MEASURED ON vfx_fit.json's ART, WHICH IS NOT NECESSARILY THE ART BEING
    PATCHED. The character frames have been re-cut twice since that file was
    written; this number is the historical justification for the band, not a
    measurement of the current build. Labelled as such rather than quietly
    reprinted as if it were fresh.

    (The X-only PHASE fit that used to live here has been deleted. It was tied
    to an 8-frame still set that no longer exists, its residual was 32 % of
    R_TRAIL -- i.e. it never constrained anything -- and leaving a stale
    8-frame instrument in a 16-frame world only invites someone to trust it.)
    """
    per = fit.get('per_frame')
    if not per:
        return None
    heights = sorted((fit['sole_row'] - p['mace'][1]) / fit['figure_height']
                     for p in per)
    return dict(n=len(per), height_lo=heights[0], height_hi=heights[-1],
                height_spread=heights[-1] - heights[0])


# ---------------------------------------------------------------------------
# Step 3: derive each direction's phase roll by hash
# ---------------------------------------------------------------------------

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_still_hashes():
    """The canonical revolution's stills, in order -- i.e. attack_S frames
    0..n-1, for whatever n that cell holds (8 in the first turnaround, 16 in
    the re-shot one). Frame 0 is the phase anchor. Returns None when the cells
    are simply not present, which is a legitimate state for a clip-cut build
    rather than an error."""
    frames_dir = CELLS_ROOT / 'attack_S' / 'frames' / 'attack' / 'S'
    if not frames_dir.is_dir():
        return None
    got = {}
    for p in frames_dir.glob('attack_S_*.png'):
        m = re.fullmatch(r'attack_S_(\d+)\.png', p.name)
        if m:
            got[int(m.group(1))] = p
    if not got or sorted(got) != list(range(len(got))):
        return None
    return [sha(got[i]) for i in range(len(got))]


def derive_rolls(project, canon, counts):
    """Per-direction phase offset, as a FRACTION OF A REVOLUTION.

    ⚑ TWO ART SHAPES, AND THE ROLL ONLY EXISTS IN ONE OF THEM.

    TURNAROUND builds (warlord3): all eight facings are exact rotations of ONE
    eight-still revolution, so attack_<D> frame 0 shows a different point of
    the spin per direction and the ribbon must be offset to match. That offset
    is derived HERE, from the image bytes, never from the registration note.

    CLIP-CUT builds (warlord2): each direction is its own 12- or 9-frame cut of
    its own clip. There is no shared still sequence and therefore no roll --
    every direction starts its own loop at its own frame 0, offset 0.

    A build that is not a clean turnaround is NOT an error: it is the other
    shape, and the whole point of locking to the 0.400 s loop is that the same
    ribbon serves both. So this returns (rolls, mode) and says which it found.
    """
    # ⚑ N IS NOT ASSUMED. The turnaround has been 8 frames at 20 fps and is now
    # 16 at 40 (a re-shot continuous take, rolled 2 frames per 45 deg). The roll
    # is derived in FRAMES against whatever the canonical sequence's length is
    # and returned as a FRACTION OF A REVOLUTION, so the frame count drops out
    # exactly as it does in the runtime phase lock.
    n = len(canon) if canon else 0
    index = {h: i for i, h in enumerate(canon)} if canon else {}
    uniform = n > 0 and all(counts[d] == n for d in DIRECTIONS)
    turnaround = len(index) == n and uniform
    reason = ''
    if turnaround:
        rolls = {}
        for d in DIRECTIONS:
            sprite_dir = project / 'sprites' / 'attack' / d
            got = {}
            if sprite_dir.is_dir():
                for p in sprite_dir.glob(f'attack_{d}_*.png'):
                    m = re.fullmatch(rf'attack_{re.escape(d)}_(\d+)\.png', p.name)
                    if m:
                        got[int(m.group(1))] = p
            if sorted(got) != list(range(n)):
                turnaround, reason = False, f'sprites/attack/{d} is not frames 0..{n - 1}'
                break
            seq = [index.get(sha(got[k]), -1) for k in range(n)]
            if -1 in seq:
                turnaround, reason = False, f'attack_{d} is not the canonical still set'
                break
            roll = seq[0]
            if seq != [(roll + k) % n for k in range(n)]:
                fail(f'attack_{d} IS built from the canonical stills but is not a '
                     f'clean rotation of them (order {seq}) -- that is a corrupt '
                     f'turnaround, not a different art shape, and the phase offset '
                     f'cannot be derived')
            rolls[d] = roll / float(n)
        if turnaround:
            return rolls, 'turnaround', f'{n} frames/revolution'
    else:
        reason = ('frame counts differ from the canonical set' if index
                  else 'no canonical still set available')
    return {d: 0.0 for d in DIRECTIONS}, 'clip-cut', reason


# ---------------------------------------------------------------------------
# Step 5: generated artefacts
# ---------------------------------------------------------------------------

def write_fit_resource(project, fit, rolls, band, counts, mode):
    lo, hi, mlo, mhi, mlo_px, mhi_px = band
    doc = {
        '_generated_by': 'runs/C-8/conductor_scripts/whirlwind_patch.py',
        '_source': 'runs/C-8/vfx_fit.json (registration + radii only)',
        '_note': ('LEVEL-BAND sweep. The ribbon runs on a constant plane at '
                  'sweep_band (of figure height, above the sole) with a helical '
                  'wobble of sweep_wobble, NOT on the drawn mace head -- whose '
                  'height wanders 4x the reference band. Bearing is the cells\' '
                  'declared construction: phase `rev` sits at bearing0 + '
                  'revolution_deg * rev, screen convention x right / y down.'),
        'canvas': fit['canvas'],
        'figure_height_px': fit['figure_height'],
        'sole_row': fit['sole_row'],
        'body_centre_x': fit['body_centre'][0],
        'r_trail_px': fit['R_TRAIL_px'],
        'r_engage_px': fit['R_ENGAGE_px'],
        'ground_squash': GROUND_SQUASH,
        'loop_seconds': LOOP_SECONDS,
        'sweep_band': SWEEP_BAND,
        'sweep_wobble': SWEEP_WOBBLE,
        'bearing0_deg': SWEEP_BEARING0_DEG,
        'revolution_deg': SWEEP_REVOLUTION_DEG,
        'art_mode': mode,
        'guard': {
            'lower_body_top': LOWER_BODY_TOP,
            'head_bottom': HEAD_BOTTOM,
            'band_lo': round(lo, 6), 'band_hi': round(hi, 6),
            'margin_below_H': round(mlo, 6), 'margin_above_H': round(mhi, 6),
            'margin_below_px': round(mlo_px, 3), 'margin_above_px': round(mhi_px, 3),
        },
        # Per-direction frame count and phase offset AS A FRACTION OF A
        # REVOLUTION -- never a frame index, so a build whose directions have
        # different frame counts (12 and 9 in the clip cut) works unchanged.
        'frames': {d: counts[d] for d in DIRECTIONS},
        'roll_rev': {d: round(rolls[d], 9) for d in DIRECTIONS},
    }
    (project / 'whirlwind_fit.json').write_text(json.dumps(doc, indent=1) + '\n')
    return doc


WHIRLWIND_GD = r'''extends Node2D
# ============================================================================
# whirlwind.gd -- the Eye-of-Reckoning whirlwind, ported to the 2D pixel keeper.
#
# GENERATED by runs/C-8/conductor_scripts/whirlwind_patch.py. Edit that script,
# not this file: a re-run overwrites this verbatim.
#
# drax, C-8. Ported from the 3D clean-room mint:
#   reincarnated-godot/scripts/wwcr_whirlwind.gd   (WW-AB, 2026-08-24)
# against the reference cut Matt pointed at:
#   ww7-gate2-cadence-ab-plk0665-1920x1080.mp4
#
# ---------------------------------------------------------------------------
# THE ONE IDEA, AND THE ONE PLACE THE PORT HAD TO DEPART FROM IT
# ---------------------------------------------------------------------------
# The only lit, tinted, continuous thing in this effect is a ribbon on the
# sweep plane. Everything at larger radius is discrete, brief and NEUTRAL. No
# disc, no decal, no radial gradient, no glow sphere. The ribbon is an ARC,
# never a closed ring -- a closed ring is a field, not a trail. The absence is
# the design.
#
# ⚑ THE SOURCE SAYS "GENERATED FROM THE WEAPON'S ACTUAL POSITION" AND THIS FILE
#   DOES NOT DO THAT, ON PURPOSE. In 3D the blade's position came off a rig and
#   was a fact; here it is eight hand-drawn stills, and measured, the drawn mace
#   head sits between 0.180 and 0.962 of figure height above the sole -- a
#   spread of 0.782 H against the reference's own sweep band of 0.195. Threading
#   a ribbon through those points does not make an ellipse, it makes a scribble.
#   So the height is a CONSTANT BAND (the 2D form of the source's SWEEP_Y plane
#   plus SWEEP_WOBBLE) and the angle is the animation frame. The radii are still
#   the conductor's measurement. Where the ribbon and the drawn mace disagree,
#   the ribbon is right and the frame is being redrawn.
#
# ---------------------------------------------------------------------------
# THE FOUR THINGS 2D CHANGED
# ---------------------------------------------------------------------------
# 1. THE SWEEP CIRCLE IS AN ELLIPSE. GROUND_SQUASH (see whirlwind_fit.json) is
#    this project's own ground-plane constant -- the same number every other
#    ground-lying VFX surface in the export is drawn with. Derivation and the
#    two rejected candidates are in whirlwind_patch.py's header.
#
# 2. Z-ORDER REPLACES THE DEPTH BUFFER. The source's disjoint-band inequality
#    survives as an inequality (it is asserted in the patch script, and its
#    margins are in whirlwind_fit.json), but what actually makes the caster
#    stand INSIDE the whirlwind in 2D is the z split: the arc is CUT at the
#    ellipse's major-axis endpoints (bearing 0 and 180, where screen dy = 0)
#    and the halves drawn on two nodes, FAR behind the keeper sprite and NEAR
#    in front of it. The cut is exact -- a quad that would straddle a crossing
#    is split at the crossing, not assigned to a side. Drawing the whole arc on
#    one layer is the defect this split exists to prevent.
#
# 3. OMEGA IS ENFORCED, NOT INTEGRATED. The source integrated OMEGA_DEG = 900
#    (2.5 rev/s). Every attack cell loops in exactly 0.400 s, which is
#    2.5 rev/s EXACTLY. So the source's authored cadence and the animation's
#    measured cadence already agree, and this file does not integrate a rate at
#    all -- the sprite owns the phase and the ribbon reads it.
#
#    ⚑ THE FRAME COUNT IS NOT PART OF THAT AND MUST NEVER BECOME PART OF IT.
#    The art has already shipped as 8 frames @ 20 fps (turnaround), 12 @ 30 and
#    9 @ 22.5 (clip cut, differing BETWEEN DIRECTIONS in one build), and 16 @ 40
#    (the re-shot continuous take). The phase below is a FRACTION of the loop,
#    so all of them drive this file unchanged; only the 0.400 s is load-bearing.
#
# 4. THE RAMP GATES INTENSITY AND EXTENT ONLY, NEVER PHASE. In 3D `_w` drove
#    the spin rate because the rig's rotation was code-driven. Here the mace is
#    at full speed on frame 0 because the SPRITE is, and a ribbon whose phase
#    lagged the sprite would slide against it every loop. SPIN_UP_S /
#    SPIN_DOWN_S therefore ramp alpha, arc extent and quantum rate, and touch
#    `_phase()` nowhere.
#
# ---------------------------------------------------------------------------
# NUMBERS -- provenance marked on every one, as in the source
# ---------------------------------------------------------------------------
#   MEASURED  = measured off the artefact named
#   CARRIED   = taken unchanged from wwcr_whirlwind.gd
#   AUTHORED  = mine, for 2D; not reference-backed
# ============================================================================

# --- CARRIED from wwcr_whirlwind.gd -----------------------------------------
## CARRIED. 10 samples at 60 fps and 900 deg/s spans ~150 deg of arc.
## In the source this span was an EMERGENT PRODUCT of sample count x frame time
## x omega -- so a frame-rate change could silently close the ring. Here it is
## an explicit constant and TRAIL_SAMPLES is a pure tessellation knob. The
## open-arc guard is now an assertion on a number instead of a hope.
const TRAIL_ARC_DEG := 150.0
## CARRIED. Blade fraction the ribbon covers: the outer 20 % only. Keeps the lit
## surface a thin annulus arc instead of a filled disc, and keeps luminance off
## the caster's body.
const TRAIL_INNER_FRAC := 0.80
## CARRIED. The taper tapers to a FLOOR, not to nothing: a band with no area
## cannot be seen. (Source's T-3 lesson, at the cost of two rounds of tuning.)
const TAPER_MIN_FRAC := 0.45
## CARRIED. Inner edge dimmer than outer: the tip moves fastest so it glows most
## (physically right) AND it keeps luminance off the caster (the mint's motive).
const CORE_INNER_ALPHA_FRAC := 0.18
## MEASURED (ww-native-eor1.semantics, via the source). Two INDEPENDENT rates --
## release decays at the release rate instead of retracing the rise.
const SPIN_UP_S := 0.70
const SPIN_DOWN_S := 0.80
## CARRIED, byte-exact. NEVER TINTED. Dust is dust. Neutrality is what stops the
## outer radius summing into a tinted ring -- it is why the quanta may live at
## R_ENGAGE at all.
const SCUFF_COLOR := Color(0.62, 0.60, 0.56)
## CARRIED. C-5 bounded.
const SPARK_LIFE := 0.12
const SCUFF_LIFE := 0.22
const MAX_SPARKS := 24
const MAX_SCUFFS := 16
## CARRIED (source 4a, SPIN-FOLLOWING SCUFFS). A quantum thrown by a blade at
## 900 deg/s takes the sweep's own tangential direction and a fraction of its
## tangential speed, then decays. Air that does not move is not evidence of a
## sweep, it is a decal that blinks. Weight-scaled: a scuff thrown during
## spin-up drifts slower than one at full song.
const SCUFF_ENTRAIN_FRAC := 0.10
const SCUFF_DRAG_TAU := 0.09
## CARRIED (source T-5, CROSS-SECTION VARIATION). Deliberately non-integer and
## mutually incommensurate, so the width profile does not repeat between
## revolutions. This matters MORE here than in 3D, not less: the sprite loop
## repeats byte-identically every 0.400 s, and with the sweep now uniform the
## ribbon has no other source of variation at all.
const XSEC_F1 := 0.7333
const XSEC_F2 := 1.6180
const XSEC_PH1 := 1.30
const XSEC_PH2 := 2.90
const XSEC_AMP := 0.075
const XSEC_MIN := 0.70
const XSEC_MAX := 0.90
## CARRIED. Bit-reproducible and independent of every other draw consumer.
const RNG_SEED := 20260825
## CARRIED. Wobble cycles per revolution. The source's SWEEP_WOBBLE rides the
## blade passes, and there are two per revolution.
const WOBBLE_CYCLES_PER_REV := 2.0

# --- MEASURED off the reference cut -----------------------------------------
# The source's three-band ramp STRUCTURE is carried (apex / body / tail as
# (S, V) plus a hue offset from the element's own hue, so `set_element` stays
# the recolour seam). The VALUES are measured off 47,772 ribbon pixels of
# ww7-gate2-cadence-ab at the 98th / 50th / 8th luminance percentile, NOT
# carried: the source's numbers are gandalf's WIND table plus a Cathedral-
# venue-coupled dark-tail override, and this reference is the amber cut on a
# different floor. Measured tail V is 0.756 -- there is no dark tail in it, so
# the source's two-surface ADD/MIX split (which exists only to put a value
# BELOW the floor's into the frame) is deliberately NOT ported. One surface.
const ELEMENT_HUE_DEG := 7.48
const RAMP_APEX_SV := Vector2(0.422, 0.994)
const RAMP_BODY_SV := Vector2(0.447, 0.898)
const RAMP_TAIL_SV := Vector2(0.459, 0.756)
const RAMP_APEX_DH := 29.17
const RAMP_BODY_DH := 6.68
const RAMP_TAIL_DH := 0.00

# --- AUTHORED for 2D --------------------------------------------------------
## AUTHORED. Pure tessellation of the 150 deg span. Not a span guard (see
## TRAIL_ARC_DEG) and not a perf knob at this count.
const TRAIL_SAMPLES := 28
## AUTHORED, AND VENUE-COUPLED -- say so out loud, as the source does for its
## own venue-coupled values. The cliffside's sunlit ground measures a luma
## median of 141/255 in the sweep footprint. An additive amber ribbon on a
## ground that bright clips toward white near the apex while the tail falls
## under the ground's own contrast, so the arc reads far shorter than the
## 150 deg it geometrically is. These two numbers trade a clipped apex for a
## readable tail; on a dark floor they would both want raising. Matt's eye.
const RIBBON_ALPHA_MAX := 0.62
const RIBBON_FADE_POW := 0.90
## AUTHORED. 2D re-author of the source's 0.22 m scuff quad. In 3D a scuff sat
## in a volumetric cloud that carried the bulk; in 2D the quanta ARE the cloud,
## so each must carry more area to read as air rather than as confetti. Stated
## rather than absorbed: this is the one place the port needed more, not less.
const SCUFF_SIZE_M := 0.55
const SPARK_LEN_M := 0.35        # AUTHORED-bounded by the source's C-5 ceiling.
## AUTHORED. Spawn rates chosen to run the CARRIED pools near-full rather than
## to a look: 16 scuffs at 0.22 s life saturate at ~73/s, 24 sparks at 0.12 s at
## ~200/s. Held well under both so the caps bind on bursts, not on the steady
## state -- the caps stay the bound they were in the source.
const SCUFF_HZ := 58.0
const SPARK_HZ := 44.0
## AUTHORED. Angular spread, about the apex bearing, that quanta are thrown into.
const SCUFF_SPREAD_DEG := 62.0
const SPARK_SPREAD_DEG := 16.0
## AUTHORED. Standing character height in metres, for the two *_M constants
## above. The source's H_STAND; used here only to convert them.
const H_STAND_M := 1.85

enum S { IDLE, RISING, SUSTAIN, FALLING }

var _state: int = S.IDLE
var _w := 0.0                       # normalized channel weight, 0..1
var _sprite: AnimatedSprite2D
var _fit: Dictionary
## Four draw layers: {far, near} x {dust, arc}. The far/near split is the
## Z-ORDER guard (see the header). The dust/arc split is a BLEND-MODE guard:
## the ribbon is additive because it is light, and the dust must NOT be --
## SCUFF_COLOR added onto the cliffside's mid-value ground would wash to a pale
## smear and the "neutral, never tinted" rule would be discharged in name only.
var _far_dust: Node2D
var _far_arc: Node2D
var _near_dust: Node2D
var _near_arc: Node2D
var _layers: Array[Node2D] = []
var _rng := RandomNumberGenerator.new()

# node-space geometry, resolved in bind() from the sprite's ACTUAL transform
var _centre := Vector2.ZERO         # sweep-plane centre: body axis X, band Y
var _r_trail := 0.0
var _r_engage := 0.0
var _wobble_px := 0.0
var _squash := 0.60
var _px_per_m := 1.0
var _bearing0 := 90.0
var _revolution_deg := -360.0

# ramp, derived from the element hue exactly as the source's set_element does
var _c_apex := Color.WHITE
var _c_body := Color.WHITE
var _c_tail := Color.WHITE

var _spin_total := 0.0              # free-running, for XSEC only
var _last_theta := 0.0
var _have_last := false
# ⚑ TWO ANCHORING FRAMES, AND THE CHOICE IS THE POINT (A2: he WALKS while
#   whirlwinding, so "where a quantum lives" stopped being a free question).
#
#   RIBBON  -- character-centred, unarguably. It is the weapon's path, and the
#              weapon is on the character. Free: the layers are children of the
#              Keeper, so it travels with him at no cost.
#   SPARKS  -- character-centred. They come off the blade, they are airborne,
#              and at SPARK_LIFE 0.12 s they are gone in 30 px of walk.
#   SCUFFS  -- GROUND-ANCHORED, stored in GLOBAL space. These are the blade
#              throwing air off the FLOOR. At walk pace (247 px/s) and
#              SCUFF_LIFE 0.22 s a character-anchored puff would slide 54 px
#              along with him -- a dust cloud towed behind a walking man, which
#              is precisely the "decal that blinks" failure the source's 4a
#              block is about, one axis along. Ground-anchoring costs one
#              to_local() per puff per draw and makes him walk THROUGH his own
#              dust, which is what a sweep leaving consequences looks like.
var _scuffs: Array = []             # {pos (GLOBAL), vel, t, life, far}
var _sparks: Array = []             # {pos (local), vel, t, life, far}
var _scuff_debt := 0.0
var _spark_debt := 0.0

## The arc, rebuilt ONCE per physics frame in `_build_arc` and consumed by both
## arc layers. Built outside `_draw` on purpose: it halves the work, and it
## makes the measurements below readable by a HEADLESS probe, where `_draw`
## never fires at all.
var _arc: Array = []
## Runtime measurement, in the source's `_meas_*` spirit: numbers the effect
## ACTUALLY exhibited, so the guards can be checked instead of admired.
var _arc_span := 0.0                # the open-arc guard, as a number
var _quads_drawn_far := 0
var _quads_drawn_near := 0
## The phase `_build_arc` actually used. Recorded because the sprite advances in
## _process and the arc is built in _physics_process, so anything that re-reads
## `_phase()` later is reading a DIFFERENT instant -- which presents as a large
## apex error the effect does not have.
var _arc_u := -1.0
# ⚑ TWO DIFFERENT HEIGHTS, AND CONFLATING THEM COSTS A FALSE ALARM.
#
#   _meas_plane_*  the SWEEP PLANE's screen Y under each sample -- centre plus
#                  wobble. THIS is "the level band", and this is what the
#                  disjoint-band guard is about. It is ~0.08 H wide.
#   _meas_arc_y_*  the screen-Y extent of the drawn ARC. A circle lying on the
#                  ground projects to an ellipse, so this is ~2*R_TRAIL*squash
#                  wide -- about 0.94 H -- BY DESIGN, and it sweeps from over
#                  the helm to the ground line exactly as the reference cut
#                  does. Asserting the guard against THIS number fails a
#                  correct effect, which is how the distinction got written
#                  down: the first version of the probe did exactly that.
var _meas_plane_lo := INF
var _meas_plane_hi := -INF
var _meas_arc_y_lo := INF
var _meas_arc_y_hi := -INF


func _arc_span_deg() -> float:
	return _arc_span


## ⚑ THE ROTATION SENSE, AS A RUNTIME ASSERTION RATHER THAN A COMMENT.
##
## Samples the apex a quarter-revolution apart and takes the 2D cross product
## of the two offsets about the sweep centre. In a Y-DOWN frame a POSITIVE
## cross product means the second sample is a quarter-turn CLOCKWISE of the
## first (right -> down -> left -> up), which is the sense the character turns.
##
## Returns [cross, +1 clockwise / -1 anticlockwise, expected_sign]. A probe
## asserts sign == expected; getting it backwards is the one defect in this
## file that a reader cannot see by inspecting geometry, because both senses
## draw an identical-looking ellipse and only the MOTION differs.
func sense_check() -> Array:
	var p0 := _ground(_theta_at(0.00), _r_trail)
	var p1 := _ground(_theta_at(0.25), _r_trail)
	var cross := p0.x * p1.y - p0.y * p1.x
	return [cross, (1 if cross > 0.0 else -1),
		(1 if _revolution_deg > 0.0 else -1)]


## The ribbon apex in node space.
func apex_point() -> Vector2:
	if _arc.is_empty():
		return Vector2.INF
	return Vector2(_arc[0]["o"])


## Canvas (512-space) pixel -> node space, through the sprite's ACTUAL transform.
var _c2n_scale := Vector2.ONE
var _c2n_off := Vector2.ZERO


func canvas_to_node(p: Vector2) -> Vector2:
	return _c2n_off + p * _c2n_scale


# ---------------------------------------------------------------------------
# binding
# ---------------------------------------------------------------------------
func bind(sprite: AnimatedSprite2D) -> void:
	_sprite = sprite
	_rng.seed = RNG_SEED
	var text := FileAccess.get_file_as_string("res://whirlwind_fit.json")
	if text.is_empty():
		push_error("whirlwind: res://whirlwind_fit.json missing or empty")
		return
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("whirlwind: whirlwind_fit.json is not an object")
		return
	_fit = parsed
	_squash = float(_fit["ground_squash"])
	_bearing0 = float(_fit["bearing0_deg"])
	_revolution_deg = float(_fit["revolution_deg"])

	# READ the sprite's transform, never assume it. The canvas->node mapping is
	# the exporter's own: `centered = false`, `offset = (-256, -400)`,
	# `scale = figure_height_px / 240`. Both centred modes are handled because
	# keeper.gd's own _socket_world() handles both.
	var s: Vector2 = _sprite.scale
	var o: Vector2 = _sprite.offset
	var half := Vector2.ZERO
	if _sprite.centered:
		var tex: Texture2D = _sprite.sprite_frames.get_frame_texture(
			_sprite.animation, 0)
		if tex != null:
			half = tex.get_size() / 2.0
	_c2n_scale = s
	_c2n_off = _sprite.position + (o - half) * s

	# ⚑ THE SWEEP PLANE. X from the figure's own body axis; Y from the BAND,
	#   measured up from the sole -- NOT from any mace row.
	var H: float = float(_fit["figure_height_px"])
	var sole: float = float(_fit["sole_row"])
	var band_row: float = sole - float(_fit["sweep_band"]) * H
	_centre = canvas_to_node(Vector2(float(_fit["body_centre_x"]), band_row))
	_r_trail = float(_fit["r_trail_px"]) * s.x
	_r_engage = float(_fit["r_engage_px"]) * s.x
	_wobble_px = float(_fit["sweep_wobble"]) * H * s.y
	_px_per_m = (H * s.x) / H_STAND_M

	# ⚑ THE Z SPLIT. z_index is RELATIVE to the Keeper (z_as_relative defaults
	# true), and the Keeper's own children are ContactShadow (-1) and
	# AnimatedSprite2D (0):
	#   FAR  at -1 -- ties with the contact shadow, and because these nodes are
	#                 added LATER they draw OVER the shadow and UNDER the sprite.
	#                 -2 was rejected: it would drop below the foreground plate.
	#   NEAR at +1 -- over the sprite, under nothing else in the Actors band.
	# Within a tie, tree order decides, so dust is added before arc on each side.
	_far_dust = _mk_layer("WhirlwindFarDust", -1, false, false, true)
	_far_arc = _mk_layer("WhirlwindFarArc", -1, true, false, false)
	_near_dust = _mk_layer("WhirlwindNearDust", 1, false, true, true)
	_near_arc = _mk_layer("WhirlwindNearArc", 1, true, true, false)

	set_element(Color.from_hsv(ELEMENT_HUE_DEG / 360.0, 0.55, 1.0))
	_set_visible(false)


func _mk_layer(nm: String, z: int, additive: bool, is_near: bool, dust: bool) -> Node2D:
	var n := Node2D.new()
	n.name = nm
	n.z_index = z
	if additive:
		var mat := CanvasItemMaterial.new()
		mat.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
		n.material = mat
	if dust:
		n.draw.connect(func(): _draw_dust(n, is_near))
	else:
		n.draw.connect(func(): _draw_arc(n, is_near))
	add_child(n)
	_layers.append(n)
	return n


## TIER-1 element parameterization, carried from the source: the three bands are
## DERIVED from the hue handed in, so fire/water/earth come out of the same code
## instead of a palette hard-coded for one element.
func set_element(c: Color) -> void:
	var hue := c.h
	_c_apex = Color.from_hsv(fposmod(hue + RAMP_APEX_DH / 360.0, 1.0),
		RAMP_APEX_SV.x, RAMP_APEX_SV.y)
	_c_body = Color.from_hsv(fposmod(hue + RAMP_BODY_DH / 360.0, 1.0),
		RAMP_BODY_SV.x, RAMP_BODY_SV.y)
	_c_tail = Color.from_hsv(fposmod(hue + RAMP_TAIL_DH / 360.0, 1.0),
		RAMP_TAIL_SV.x, RAMP_TAIL_SV.y)
	# Scuffs are NOT touched. Deliberately. See SCUFF_COLOR.


func begin() -> void:
	if _state == S.IDLE:
		_have_last = false
		_meas_plane_lo = INF
		_meas_plane_hi = -INF
		_meas_arc_y_lo = INF
		_meas_arc_y_hi = -INF
	_state = S.RISING
	_set_visible(true)


func end() -> void:
	if _state != S.IDLE:
		_state = S.FALLING


func channel_weight() -> float:
	return _w


func state_name() -> String:
	return ["IDLE", "RISING", "SUSTAIN", "FALLING"][_state]


func _set_visible(v: bool) -> void:
	for n in _layers:
		n.visible = v


# ---------------------------------------------------------------------------
# ⚑ PHASE LOCK. The sprite owns the phase; this function only reads it.
#
# The phase is a FRACTION OF A REVOLUTION, never a frame index:
#   rev = (frame + frame_progress) / frames_in_this_direction + roll_rev
# taken mod 1. `frame_progress` (Godot 4.2+) is the fraction elapsed of the
# CURRENT displayed frame. There is no accumulator, so it cannot drift: a
# dropped frame or a time-scale change moves the sprite and the ribbon together
# by construction.
#
# ⚑ AND BECAUSE IT IS A FRACTION, THE FRAME COUNT DROPS OUT. Shipped so far:
#   8 @ 20 fps (turnaround), 12 @ 30 and 9 @ 22.5 for N/NE/NW (clip cut --
#   different per BUILD and per DIRECTION), and 16 @ 40 (the re-shot continuous
#   take). All loop in exactly 0.400 s, and that is the only thing this effect
#   needs, which is why one ribbon drops onto any of them with no code change.
#
# `roll_rev` is the direction's phase offset, in revolutions. It is non-zero
# only for a turnaround build, where all eight facings are rotations of ONE
# still sequence; the patch derives it from the image bytes.
# ---------------------------------------------------------------------------
func _phase() -> float:
	var anim := String(_sprite.animation)
	if not anim.begins_with("attack_"):
		return -1.0
	var d := anim.substr(7)
	var counts: Dictionary = _fit["frames"]
	if not counts.has(d):
		return -1.0
	var n := float(counts[d])
	if n <= 0.0:
		return -1.0
	return fposmod((float(_sprite.frame) + _sprite.get_frame_progress()) / n
		+ float(_fit["roll_rev"][d]), 1.0)


## The sweep bearing at revolution fraction `rev`. Closed form -- the sweep is
## uniform, so there is no interpolation table and `_u_for_theta` is its exact
## algebraic inverse.
func _theta_at(rev: float) -> float:
	return _bearing0 + _revolution_deg * rev


func _u_for_theta(theta: float) -> float:
	return (theta - _bearing0) / _revolution_deg


## The helical wobble of the sweep plane at a given bearing, in node px. Carried
## from the source's SWEEP_WOBBLE and evaluated PER SAMPLE, not per frame: the
## height a sample had is a fact about when the blade was there, and evaluating
## it at the current phase instead would make the whole stored arc breathe in
## unison -- the same defect the source's T-5 block warns about for width.
func _wobble(theta_deg: float) -> float:
	return _wobble_px * sin(deg_to_rad(
		(theta_deg - _bearing0) * WOBBLE_CYCLES_PER_REV))


## Screen offset of a point on the sweep plane. THE ELLIPSE, in one place.
##
## ⚑ THE SIGN CONVENTION LIVES HERE, AND EVERYTHING ELSE INHERITS IT. Y is
## DOWN, so sin(theta) > 0 is the BOTTOM of the screen -- the side NEAREST the
## camera. Walking theta upward therefore runs
##     0 RIGHT -> 90 BOTTOM -> 180 LEFT -> 270 TOP,
## which is CLOCKWISE to the viewer. So a POSITIVE `revolution_deg` spins the
## ribbon clockwise on screen and a NEGATIVE one counter-clockwise.
##
## ⚑ THE CURRENT ART TURNS COUNTER-CLOCKWISE, SO `revolution_deg` IS NEGATIVE,
## AND THAT IS A RULING RATHER THAN A MEASUREMENT ARTEFACT. Matt, 2026-09-21:
## a RIGHT-HANDER turns counter-clockwise -- the forehand sweep starts on the
## right and crosses left and the body keeps turning left, the way right-handed
## hammer and discus throwers rotate counter-clockwise seen from above. The
## previous build turned clockwise, i.e. a repeated BACKHAND, and was fixed by
## playing the 16-frame revolution in REVERSE (which flips the sense and keeps
## the handedness) rather than by mirroring (which would flip the sense and
## swap the hands -- a different, separately-held defect).
##
## So this constant has legitimately been both signs. Do not "restore" it from
## memory: measure the ART (see the shield test documented at the constant) and
## follow it. `sense_check()` only proves the geometry matches this constant --
## it passes at either sign and can never tell you the art disagrees.
func _ground(theta_deg: float, r: float) -> Vector2:
	var a := deg_to_rad(theta_deg)
	return Vector2(cos(a) * r, sin(a) * r * _squash + _wobble(theta_deg))


func _xsec_inner(spin_deg: float) -> float:
	var rev := spin_deg / 360.0
	var v := TRAIL_INNER_FRAC + XSEC_AMP * (
		sin(rev * TAU * XSEC_F1 + XSEC_PH1) * 0.6
		+ sin(rev * TAU * XSEC_F2 + XSEC_PH2) * 0.4)
	return clampf(v, XSEC_MIN, XSEC_MAX)


# ---------------------------------------------------------------------------
func _physics_process(delta: float) -> void:
	match _state:
		S.RISING:
			_w = minf(1.0, _w + delta / SPIN_UP_S)
			if _w >= 1.0:
				_state = S.SUSTAIN
		S.SUSTAIN:
			_w = 1.0
		S.FALLING:
			_w = maxf(0.0, _w - delta / SPIN_DOWN_S)
			if _w <= 0.0 and _scuffs.is_empty() and _sparks.is_empty():
				_state = S.IDLE
				_set_visible(false)

	var u := _phase()
	if u >= 0.0:
		var th := _theta_at(u)
		if _have_last:
			_spin_total += absf(th - _last_theta)
		_last_theta = th
		_have_last = true
		if _state != S.IDLE:
			# `_w` is applied INSIDE _emit_quanta (it scales both the rate and
			# the entrainment speed), so it is not applied to delta here as well.
			_emit_quanta(delta, th, u)

	_age_pools(delta)
	_build_arc()
	if _state != S.IDLE:
		for n in _layers:
			n.queue_redraw()


func _emit_quanta(delta: float, theta_apex: float, _u: float) -> void:
	# ⚑ THE ARITHMETIC, carried from the source's 4a block and re-evaluated in 2D:
	#   omega    = TAU / 0.400 s = 15.7080 rad/s  (the source's exact figure)
	#   v_blade  = omega * R_ENGAGE
	#   v0       = SCUFF_ENTRAIN_FRAC * v_blade, decaying at SCUFF_DRAG_TAU
	# and `_w` multiplies the rate, so coherence is with the CURRENT rotation
	# rather than with a constant.
	var omega := TAU / float(_fit["loop_seconds"])
	var v_blade := omega * _r_engage
	var sgn := signf(_revolution_deg)

	_scuff_debt += delta * SCUFF_HZ * _w
	while _scuff_debt >= 1.0 and _scuffs.size() < MAX_SCUFFS:
		_scuff_debt -= 1.0
		var th := theta_apex + _rng.randf_range(-SCUFF_SPREAD_DEG, SCUFF_SPREAD_DEG)
		var rr := _r_engage * _rng.randf_range(0.86, 1.04)
		var a := deg_to_rad(th)
		# tangent to the ellipse at th, in the sweep's own direction
		var tang := Vector2(-sin(a), cos(a) * _squash).normalized() * sgn
		_scuffs.append({
			# GLOBAL: this puff stays on the floor where the blade threw it.
			"pos": to_global(_centre + _ground(th, rr)),
			"vel": tang * v_blade * SCUFF_ENTRAIN_FRAC * _w,
			"t": 0.0, "life": SCUFF_LIFE,
			"far": sin(a) < 0.0,
			"sz": _rng.randf_range(0.72, 1.35),
		})

	_spark_debt += delta * SPARK_HZ * _w
	while _spark_debt >= 1.0 and _sparks.size() < MAX_SPARKS:
		_spark_debt -= 1.0
		var th2 := theta_apex + _rng.randf_range(-SPARK_SPREAD_DEG, SPARK_SPREAD_DEG)
		var a2 := deg_to_rad(th2)
		var rr2 := _r_trail * _rng.randf_range(0.98, 1.22)
		var tang2 := Vector2(-sin(a2), cos(a2) * _squash).normalized() * sgn
		var out := Vector2(cos(a2), sin(a2) * _squash).normalized()
		_sparks.append({
			"pos": _centre + _ground(th2, rr2),
			"vel": (tang2 * 0.82 + out * 0.18).normalized()
				* v_blade * _rng.randf_range(0.10, 0.22) * _w,
			"t": 0.0, "life": SPARK_LIFE,
			"far": sin(a2) < 0.0,
		})


func _age_pools(delta: float) -> void:
	for pool: Array in [_scuffs, _sparks]:
		var i: int = pool.size() - 1
		while i >= 0:
			var q: Dictionary = pool[i]
			q["t"] = float(q["t"]) + delta
			if float(q["t"]) >= float(q["life"]):
				pool.remove_at(i)
			else:
				q["pos"] = Vector2(q["pos"]) + Vector2(q["vel"]) * delta
				q["vel"] = Vector2(q["vel"]) * exp(-delta / SCUFF_DRAG_TAU)
			i -= 1


# ---------------------------------------------------------------------------
# GEOMETRY
# ---------------------------------------------------------------------------
## ⚑ THE ARC IS CUT AT THE ELLIPSE'S MAJOR-AXIS ENDPOINTS, NOT BINNED BY QUAD.
##
## A quad whose two ends straddle bearing 0 or 180 belongs to NEITHER half; if
## it is assigned to one, the seam between the halves jitters by up to one
## quad-width every frame and the character's silhouette visibly "pops" through
## the ribbon. So the crossings are inserted as real samples, and every quad
## then lies wholly on one side. The near/far test is the sign of sin(theta):
## dy < 0 is behind.
##
## Built once per PHYSICS frame, not once per draw: it halves the work, and a
## headless probe can read `_arc_span` / `_quads_drawn_*` / the band
## measurements without `_draw` ever firing.
func _build_arc() -> void:
	_arc.clear()
	_arc_span = 0.0
	_quads_drawn_far = 0
	_quads_drawn_near = 0
	_arc_u = -1.0
	if _w <= 0.001:
		return
	var u_apex := _phase()
	if u_apex < 0.0:
		return
	_arc_u = u_apex
	var sgn := signf(_revolution_deg)
	var th_apex := _theta_at(u_apex)
	# extent ramps with the channel weight: a spinning-up blade has not yet laid
	# a full arc behind it.
	var span := TRAIL_ARC_DEG * (0.35 + 0.65 * _w)

	var bearings: Array[float] = []
	for i in TRAIL_SAMPLES + 1:
		bearings.append(th_apex - sgn * span * (float(i) / float(TRAIL_SAMPLES)))
	# insert the 0 / 180 crossings that fall inside the span
	var lo: float = minf(th_apex, bearings[bearings.size() - 1])
	var hi: float = maxf(th_apex, bearings[bearings.size() - 1])
	var k := int(floor(lo / 180.0)) - 1
	while float(k) * 180.0 <= hi + 1.0:
		var cross := float(k) * 180.0
		if cross > lo and cross < hi:
			bearings.append(cross)
		k += 1
	# ⚑ APEX FIRST. `age` and the whole colour ramp are indexed off position in
	# this array, so the order is load-bearing, not cosmetic. With sgn = -1
	# (theta DECREASES with u) the trail lies at LARGER theta, so ascending
	# order already puts the apex at index 0; with sgn = +1 it is the reverse.
	# Getting this backwards paints the tail colour on the apex and reports an
	# arc span of zero -- which is how it was caught.
	bearings.sort()
	if sgn > 0.0:
		bearings.reverse()
	# ⚑ DEDUPE. When an inserted 0/180 crossing lands on (or within float dust
	# of) one of the uniform samples, the two coincide and the quad between
	# them has zero area -- Godot answers that with "Invalid polygon data,
	# triangulation failed" on the frame it happens, which is intermittent and
	# looks like a mystery until you notice it tracks the arc's span ramp.
	var uniq: Array[float] = []
	for th: float in bearings:
		if uniq.is_empty() or absf(th - uniq[uniq.size() - 1]) > 1e-4:
			uniq.append(th)
	bearings = uniq

	for th: float in bearings:
		var age: float = clampf(absf(th_apex - th) / maxf(span, 0.001), 0.0, 1.0)
		var r_out := _r_trail
		var inner_frac := _xsec_inner(_spin_total - absf(th_apex - th))
		var taper: float = maxf(TAPER_MIN_FRAC, pow(1.0 - age, 0.75))
		var r_in := r_out - (r_out * (1.0 - inner_frac)) * taper
		var po := _centre + _ground(th, r_out)
		_arc.append({
			"th": th, "age": age,
			"o": po,
			"i": _centre + _ground(th, r_in),
			"behind": sin(deg_to_rad(th)) < 0.0,
		})
		var plane_y := _centre.y + _wobble(th)
		_meas_plane_lo = minf(_meas_plane_lo, plane_y)
		_meas_plane_hi = maxf(_meas_plane_hi, plane_y)
		_meas_arc_y_lo = minf(_meas_arc_y_lo, po.y)
		_meas_arc_y_hi = maxf(_meas_arc_y_hi, po.y)

	# the guards, as measurements rather than adjectives
	_arc_span = absf(th_apex - float(_arc[_arc.size() - 1]["th"]))
	for n in range(_arc.size() - 1):
		if bool(_arc[n]["behind"]):
			_quads_drawn_far += 1
		else:
			_quads_drawn_near += 1


# ---------------------------------------------------------------------------
# DRAWING
# ---------------------------------------------------------------------------
func _draw_dust(layer: Node2D, is_near: bool) -> void:
	_draw_scuffs(layer, is_near)


func _draw_arc(layer: Node2D, is_near: bool) -> void:
	_draw_ribbon(layer, is_near)
	_draw_sparks(layer, is_near)


func _draw_ribbon(layer: Node2D, is_near: bool) -> void:
	for n in range(_arc.size() - 1):
		var p: Dictionary = _arc[n]
		var q: Dictionary = _arc[n + 1]
		# both ends are on the same side by construction (crossings are samples)
		if bool(p["behind"]) == is_near:
			continue
		var ca := _ramp(float(p["age"]))
		var cb := _ramp(float(q["age"]))
		var aa := _alpha(float(p["age"]))
		var ab := _alpha(float(q["age"]))
		var quad := PackedVector2Array([p["i"], p["o"], q["o"], q["i"]])
		var cols := PackedColorArray([
			Color(ca.r, ca.g, ca.b, aa * CORE_INNER_ALPHA_FRAC),
			Color(ca.r, ca.g, ca.b, aa),
			Color(cb.r, cb.g, cb.b, ab),
			Color(cb.r, cb.g, cb.b, ab * CORE_INNER_ALPHA_FRAC),
		])
		layer.draw_polygon(quad, cols)


func _ramp(age: float) -> Color:
	if age < 0.35:
		return _c_apex.lerp(_c_body, age / 0.35)
	return _c_body.lerp(_c_tail, (age - 0.35) / 0.65)


func _alpha(age: float) -> float:
	return RIBBON_ALPHA_MAX * _w * pow(1.0 - age, RIBBON_FADE_POW)


func _draw_scuffs(layer: Node2D, is_near: bool) -> void:
	var rad := SCUFF_SIZE_M * _px_per_m * 0.5
	for q in _scuffs:
		if bool(q["far"]) == is_near:
			continue
		var f := float(q["t"]) / float(q["life"])
		# rise then fall; dust is brief and it never peaks opaque.
		var a := 0.30 * sin(f * PI) * _w
		var r := rad * float(q["sz"]) * (0.65 + 0.55 * f)
		var p := layer.to_local(Vector2(q["pos"]))   # stored GLOBAL; see above
		layer.draw_circle(p, r,
			Color(SCUFF_COLOR.r, SCUFF_COLOR.g, SCUFF_COLOR.b, a * 0.55))
		layer.draw_circle(p, r * 0.55,
			Color(SCUFF_COLOR.r, SCUFF_COLOR.g, SCUFF_COLOR.b, a * 0.45))


func _draw_sparks(layer: Node2D, is_near: bool) -> void:
	var maxlen := SPARK_LEN_M * _px_per_m
	for q in _sparks:
		if bool(q["far"]) == is_near:
			continue
		var f := float(q["t"]) / float(q["life"])
		var v := Vector2(q["vel"])
		var tail: Vector2 = v.normalized() * minf(maxlen, v.length() * SPARK_LIFE * 0.9)
		var a := (1.0 - f) * 0.9 * _w
		layer.draw_line(Vector2(q["pos"]), Vector2(q["pos"]) - tail,
			Color(_c_apex.r, _c_apex.g, _c_apex.b, a), 1.6)
'''


def write_whirlwind_gd(project):
    path = project / 'scripts' / 'whirlwind.gd'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(WHIRLWIND_GD)
    uid = path.with_suffix('.gd.uid')
    if uid.exists():
        uid.unlink()


# ---------------------------------------------------------------------------
# Step 6: keeper.gd
# ---------------------------------------------------------------------------

MARKER = '# PATCH(drax whirlwind_patch): Eye of Reckoning whirlwind VFX'

READY_ANCHOR = '''    sprite.animation_finished.connect(_animation_finished)
    _play_state()
'''

READY_BLOCK = '''    ''' + MARKER + '''
    whirlwind = preload("res://scripts/whirlwind.gd").new()
    whirlwind.name = "Whirlwind"
    add_child(whirlwind)
    whirlwind.bind(sprite)
'''

VAR_ANCHOR = 'var fallback_remaining: float = -1.0\n'
VAR_BLOCK = 'var whirlwind: Node2D\n'

# Both anchors below are attack_patch.py's own inserted blocks. Anchoring on
# them is what makes "must run after attack_patch.py" mechanical. The hold
# anchor is deliberately the SHORT release clause rather than the whole block:
# the rest of that block is the A2 travel logic, which this patch has no
# business pinning the exact text of.
ATTACK_HOLD_ANCHOR = '''        if not Input.is_action_pressed("attack"):
            state = "idle"
            _play_state()
            return
'''

ATTACK_HOLD_PATCHED = '''        if not Input.is_action_pressed("attack"):
            state = "idle"
            if whirlwind != null:
                whirlwind.end()
            _play_state()
            return
'''

ATTACK_TRIGGER_ANCHOR = '''    if Input.is_action_just_pressed("attack"):
        state = "attack"
        velocity = Vector2.ZERO
        _play_state()
        return
'''

ATTACK_TRIGGER_PATCHED = '''    if Input.is_action_just_pressed("attack"):
        state = "attack"
        velocity = Vector2.ZERO
        _play_state()
        if whirlwind != null:
            whirlwind.begin()
        return
'''


def patch_keeper_gd(project):
    path = project / 'scripts' / 'keeper.gd'
    text = path.read_text()
    if MARKER in text:
        return False

    for name, anchor in (('_ready animation hookup', READY_ANCHOR),
                         ('fallback_remaining declaration', VAR_ANCHOR),
                         ('attack hold block', ATTACK_HOLD_ANCHOR),
                         ('attack trigger block', ATTACK_TRIGGER_ANCHOR)):
        if text.count(anchor) != 1:
            fail(f'keeper.gd: expected exactly one occurrence of the {name} '
                 f'(found {text.count(anchor)}) -- unrecognized controller shape, '
                 f'refusing to guess where to bind the whirlwind')

    text = text.replace(VAR_ANCHOR, VAR_ANCHOR + VAR_BLOCK, 1)
    text = text.replace(READY_ANCHOR, READY_ANCHOR + READY_BLOCK, 1)
    text = text.replace(ATTACK_HOLD_ANCHOR, ATTACK_HOLD_PATCHED, 1)
    text = text.replace(ATTACK_TRIGGER_ANCHOR, ATTACK_TRIGGER_PATCHED, 1)
    path.write_text(text)
    return True


# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 2:
        fail('usage: python3 whirlwind_patch.py <path to exported godot dir>')
    project = Path(sys.argv[1]).resolve()
    if not project.is_dir():
        fail(f'not a directory: {project}')

    counts = require_attack_patched(project)
    shapes = sorted(set(counts.values()))
    print(f'whirlwind_patch: {project} is attack-patched; every direction loops in '
          f'{LOOP_SECONDS}s, frame counts {shapes}')

    fit = load_fit()
    band = check_band(fit)
    lo, hi, mlo, mhi, mlo_px, mhi_px = band
    print(f'whirlwind_patch: LEVEL BAND {SWEEP_BAND} +/- {SWEEP_WOBBLE} H '
          f'-> [{lo:.4f}, {hi:.4f}] H')
    print(f'  disjoint-band guard: {mlo:.4f} H ({mlo_px:.1f} px) above the hips, '
          f'{mhi:.4f} H ({mhi_px:.1f} px) below the chin -- both must be > 0')

    ev = report_level_band_evidence(fit)
    if ev:
        print(f'  why a band at all: mace-head height across vfx_fit.json\'s '
              f'{ev["n"]} stills spans [{ev["height_lo"]:.3f}, {ev["height_hi"]:.3f}] H, '
              f'spread {ev["height_spread"]:.3f} vs the reference band\'s 0.195 '
              f'-- historical justification, NOT a measurement of this build')

    canon = canonical_still_hashes()
    rolls, mode, reason = derive_rolls(project, canon, counts)
    if mode == 'turnaround':
        print('whirlwind_patch: art mode TURNAROUND; per-direction phase offset '
              'derived by hash: '
              + ' '.join(f'{d}={rolls[d]:.4f}rev' for d in DIRECTIONS)
              + f'   [{reason}]')
    else:
        print(f'whirlwind_patch: art mode CLIP-CUT ({reason}); each direction is its '
              f'own cut, so every phase offset is 0 -- per-direction frame counts '
              + ' '.join(f'{d}={counts[d]}' for d in DIRECTIONS))
    sense = 'CLOCKWISE on screen' if SWEEP_REVOLUTION_DEG > 0 else 'ANTICLOCKWISE on screen'
    print(f'whirlwind_patch: sweep {SWEEP_REVOLUTION_DEG:+.1f} deg/loop from '
          f'{SWEEP_BEARING0_DEG:.1f} deg = {sense} '
          f'({abs(SWEEP_REVOLUTION_DEG) / LOOP_SECONDS:.0f} deg/s), squash '
          f'{GROUND_SQUASH}')

    write_fit_resource(project, fit, rolls, band, counts, mode)
    print(f'whirlwind_patch: wrote {project / "whirlwind_fit.json"}')

    write_whirlwind_gd(project)
    print(f'whirlwind_patch: wrote {project / "scripts" / "whirlwind.gd"}')

    if patch_keeper_gd(project):
        print(f'whirlwind_patch: patched {project / "scripts" / "keeper.gd"} '
              f'(build in _ready, begin/end on the attack transitions)')
    else:
        print(f'whirlwind_patch: {project / "scripts" / "keeper.gd"} already '
              f'patched (idempotent no-op)')

    print('whirlwind_patch: done.')


if __name__ == '__main__':
    main()
