-- corpus_js4b_rule_stamping_2026_10_06.sql
-- J-S4b (gd-eor-warlord-referent) rule stamping. Author: gamora (rule owner). APPLIED BY: elrond (corpus.db steward).
-- Math note: reincarnated-engine/src/reincarnated/simulation/math/join1-b0n-numeric-selfjoin-2026-10-06.md s3.
-- Generated by reincarnated-engine/src/reincarnated/simulation/scripts/gamora_join1_js4b_rule_stamping_2026_10_06.py
-- DUAL-COLUMN LAW BY CONSTRUCTION: UPDATE-only; SET touches {rdr_value, rule_id, rule_version_applied} only;
-- source_value is never in a SET clause. Idempotent: every UPDATE requires rule_id IS NULL AND rdr_value IS NULL.
-- Input corpus.db FILE sha256 expected: 0d73475aea0f5f290a754a501e58d83af06958259fae4621317320f0fb285d07
-- Input J-S4b ROWSET expected: 66250f2d138be8b13e780c2f3ab6d35f637998ef7faa3f45f2ed31a8f69665b7
BEGIN TRANSACTION;
SELECT 'GUARD pre: OTHER kits stamped-row count=' || COUNT(*) || ' / sum(rdr)=' || TOTAL(rdr_value) FROM kit_numeric WHERE kit_id <> 'gd-eor-warlord-referent' AND rule_id IS NOT NULL;
SELECT 'GUARD pre: J-S4b unstamped rows (expect 104)=' || COUNT(*) FROM kit_numeric WHERE kit_id='gd-eor-warlord-referent' AND rdr_value IS NULL AND rule_id IS NULL;
-- R-T2 on gd_seconds: 14 rows (eor_tick_period_s, eor_period_at_100pct_as_s, eor_channel_tail_s, eor_bleed_base_duration_s, soulfire_period_s, vires_might_cooldown_s, war_cry_cooldown_s, war_cry_duration_s, blitz_cooldown_s, ascension_cooldown_s, ascension_duration_s, violent_delights_cooldown_s, guardian_of_empyrion_cooldown_s, deathstalker_cooldown_s)
UPDATE kit_numeric SET rdr_value = source_value, rule_id = 'R-T2', rule_version_applied = 1
 WHERE kit_id = 'gd-eor-warlord-referent' AND source_scale = 'gd_seconds' AND rule_id IS NULL AND rdr_value IS NULL;
SELECT 'GUARD post: J-S4b rows stamped (expect 14)=' || COUNT(*) FROM kit_numeric WHERE kit_id='gd-eor-warlord-referent' AND rule_id IS NOT NULL;
SELECT 'GUARD post: J-S4b stamped rows with rdr_value <> source_value (expect 0)=' || COUNT(*) FROM kit_numeric WHERE kit_id='gd-eor-warlord-referent' AND rule_id IS NOT NULL AND rdr_value <> source_value;
SELECT 'GUARD post: OTHER kits stamped-row count (must equal the pre value)=' || COUNT(*) || ' / sum(rdr)=' || TOTAL(rdr_value) FROM kit_numeric WHERE kit_id <> 'gd-eor-warlord-referent' AND rule_id IS NOT NULL;
COMMIT;
