#!/usr/bin/env python3
"""C-9 BV2F ARENA (R-C9-374/376): stage THE EXISTING CLIFFSIDE / ENEMY VFX the arena reuses into one compact pack.

Nothing is drawn here: every frame is copied (trimmed to its alpha bbox; the large ground phases halved) from
  * C-9 en_e2/vfx/<id>_atlas.png + _frames.json   the per-element enemy flipbooks (premultiplied RGBA, 100.6 px/m)
  * C-7 cliffside_v45/vfx/lightning_blast/        the cliffside lightning strike (palette-index frames, kit.json holds)
  * C-7 cliffside_v45/vfx/blackwater_cocktail_e3/ the V45 Blackwater cocktail: flask, floor field, lick pulse
and packed onto 4096^2 pages. Every source file's sha256 is recorded in the index; the runtime draws them as
camera-facing billboards / ground quads with their own frames, timings and palettes (scripts/arena/arena_enemy_vfx.gd).
Output (gitignored, regenerated by this tool): godot/kc2/vfx_x/{index.json, page_N.png}
usage: python3 tools/arena_stage_vfx.py"""
import hashlib, json, os, re
from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.abspath(os.path.join(HERE, "..", "..", ".."))           # .../burst/runs
EN = os.path.join(RUNS, "C-9", "en_e2", "vfx")
C7 = os.path.join(RUNS, "C-7", "cliffside_v45", "vfx")
OUT = os.path.join(HERE, "kc2", "vfx_x")
PAGE = 4096
PPM = 100.617553710938

# element atlas -> the phases the arena draws (R-C9-376 mapping)
EN_USE = {
    "en_u_flame": ["slash", "bolt", "burst", "ring_burst", "ring_smoke", "aura"],
    "en_r_flame": ["bolt", "burst"],
    "en_n_frost": ["slash", "bolt", "burst", "ring_burst", "ring_smoke", "aura"],
    "en_b_blight": ["slash", "bolt", "burst", "ring_burst", "ring_smoke", "ring_tele"],
    "en_v_void": ["slash", "bolt", "burst", "ring_burst", "ring_smoke", "aura"],
    "en_d_aether": ["slash", "bolt", "burst", "ring_burst", "ring_smoke", "aura"],
    "en_s_stone": ["slash", "bolt", "burst", "ring_burst", "ring_smoke"],
    "en_g_mud": ["burst", "ring_smoke"],
    "en_q_storm": ["bolt", "burst"],
    "en_o_bone": ["aura"],
}
HALVE = {"aura", "ring_burst", "ring_tele", "ring_smoke"}     # big soft ground/smoke frames: half resolution


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def palette_of(tres):
    cols = []
    for i in range(4):
        m = re.search(r"palette_%d = Color\(([^)]*)\)" % i, open(tres).read())
        cols.append([float(x) for x in m.group(1).split(",")])
    return cols


class Packer:
    def __init__(self):
        self.pages = [Image.new("RGBA", (PAGE, PAGE), (0, 0, 0, 0))]
        self.x = self.y = self.row_h = 0

    def put(self, im):
        w, h = im.size
        if self.x + w > PAGE:
            self.x, self.y, self.row_h = 0, self.y + self.row_h + 1, 0
        if self.y + h > PAGE:
            self.pages.append(Image.new("RGBA", (PAGE, PAGE), (0, 0, 0, 0)))
            self.x = self.y = self.row_h = 0
        self.pages[-1].paste(im, (self.x, self.y))
        r = [len(self.pages) - 1, self.x, self.y, w, h]
        self.x += w + 1
        self.row_h = max(self.row_h, h)
        return r


def trimmed(im):
    bb = im.getchannel("A").getbbox()
    if bb is None:
        return None, (0, 0)
    return im.crop(bb), (bb[0], bb[1])


pk = Packer()
index = {"page_px": PAGE, "sources": {}, "palettes": {}, "sets": {}}

# ---- en_e2 element atlases (premultiplied) ----
for aid, phases in EN_USE.items():
    ap, fp = os.path.join(EN, aid + "_atlas.png"), os.path.join(EN, aid + "_frames.json")
    index["sources"][aid] = {"atlas": ap, "atlas_sha256": sha(ap), "frames": fp, "frames_sha256": sha(fp)}
    meta = json.load(open(fp))
    atlas = Image.open(ap).convert("RGBA")
    for ph in phases:
        pm = meta["phases"][ph]
        k = 0.5 if ph in HALVE else 1.0
        frames = []
        for fr in pm["frames"]:
            x, y, w, h = fr["rect"]
            im = atlas.crop((x, y, x + w, y + h))
            t, (ox, oy) = trimmed(im)
            if t is None:
                frames.append(None)
                continue
            if k != 1.0:
                t = t.resize((max(1, round(t.width * k)), max(1, round(t.height * k))), Image.LANCZOS)
            r = pk.put(t)
            frames.append({"page": r[0], "rect": r[1:], "off": [(fr["offset_px"][0] + ox) * k, (fr["offset_px"][1] + oy) * k]})
        index["sets"]["%s/%s" % (aid, ph)] = {"mode": "premul", "ppm": float(pm["px_per_m"]) * k, "plane": pm["plane"],
            "loop": bool(pm["loop"]), "fps": float(pm["fps"]), "frames": frames}

# ---- cliffside lightning_blast (palette index frames) ----
lb = os.path.join(C7, "lightning_blast")
kit = json.load(open(os.path.join(lb, "kit.json")))
index["sources"]["lightning_blast"] = {"kit": os.path.join(lb, "kit.json"), "kit_sha256": sha(os.path.join(lb, "kit.json")),
    "body_tres_sha256": sha(os.path.join(lb, "materials", "Body.tres")), "files": {}}
index["palettes"]["lightning_blast"] = palette_of(os.path.join(lb, "materials", "Body.tres"))
index["palettes"]["lightning_blast_add"] = palette_of(os.path.join(lb, "materials", "Additive.tres"))
for ph in ("cast", "travel", "impact", "residual"):
    frames, holds = [], []
    for fr in kit["phases"][ph]["frames"]:
        p = os.path.join(lb, fr["file"])
        index["sources"]["lightning_blast"]["files"][fr["file"]] = sha(p)
        im = Image.open(p).convert("RGBA")
        t, (ox, oy) = trimmed(im)
        r = pk.put(t)
        frames.append({"page": r[0], "rect": r[1:], "off": [ox - im.width / 2.0, oy - im.height / 2.0]})
        holds.append(int(fr.get("hold_frames", 1)))
    index["sets"]["lightning_blast/" + ph] = {"mode": "palette", "palette": "lightning_blast",
        "ppm": PPM / float(kit["phase_scale"].get(ph, 1.0)), "plane": "billboard", "loop": ph == "travel",
        "holds_60": holds, "frames": frames, "speed_px_s": kit["phases"][ph].get("speed_px_s")}
index["sets"]["lightning_blast/layers"] = kit["layers"]
index["sets"]["lightning_blast/ground_squash"] = kit.get("ground_squash", 0.6)

# ---- V45 Blackwater cocktail (flask straight; field + pulse palette) ----
bw = os.path.join(C7, "blackwater_cocktail_e3")
index["sources"]["blackwater_cocktail_e3"] = {"files": {}}
index["palettes"]["cocktail_field"] = palette_of(os.path.join(bw, "materials", "Field.tres"))
index["palettes"]["cocktail_pulse"] = palette_of(os.path.join(bw, "materials", "Pulse.tres"))
for name, rel, mode, pal in (("flask", "primitives/flask.png", "premul", None),
                             ("field", "derived/field.png", "palette", "cocktail_field"),
                             ("pulse", "primitives/pulse.png", "palette", "cocktail_pulse")):
    p = os.path.join(bw, rel)
    index["sources"]["blackwater_cocktail_e3"]["files"][rel] = sha(p)
    im = Image.open(p).convert("RGBA")
    if mode == "premul":                         # straight alpha -> premultiplied, as the pack draws
        px = im.load()
        for yy in range(im.height):
            for xx in range(im.width):
                r, g, b, a = px[xx, yy]
                px[xx, yy] = (r * a // 255, g * a // 255, b * a // 255, a)
    t, (ox, oy) = trimmed(im)
    r = pk.put(t)
    index["sets"]["cocktail/" + name] = {"mode": mode, "palette": pal, "src_px": [im.width, im.height],
        "used_w": t.width, "frames": [{"page": r[0], "rect": r[1:], "off": [ox - im.width / 2.0, oy - im.height / 2.0]}]}

os.makedirs(OUT, exist_ok=True)
index["pages"] = []
for i, pg in enumerate(pk.pages):
    fn = os.path.join(OUT, "page_%d.png" % i)
    pg.save(fn, compress_level=1)
    index["pages"].append({"file": "page_%d.png" % i, "sha256": sha(fn)})
json.dump(index, open(os.path.join(OUT, "index.json"), "w"), indent=1)
print("staged %d sets on %d pages -> %s" % (len(index["sets"]), len(pk.pages), OUT))
