extends SceneTree
## C-9 R-C9-128 / R-C9-133: THE PORT'S PARAMETERS AS DATA, for kc2_play's 2D whirlwind (the KC2 drax). Binds the
## ported effect (whirlwind_fx.gd) to one character exactly as the Barrow does and writes everything it runs on:
## every constant of the source (verbatim), every length after scaling to this character, the weapon-tip sampling
## (bone, head offset, length), the spin, the channel, and the tint's derived ramp.
##   Godot --path godot ... --script tools/dump_whirlwind_params.gd -- --as-web --c warlord --out FILE.json
##   ... -- --as-web --c barbarian --armor gladc --dual --out FILE.json     (two tips, weapon_r + weapon_l)
const LENGTH_VARS := ["R_ENGAGE", "R_TRAIL", "R_GRIP_SWEEP", "SWEEP_Y", "SWEEP_WOBBLE", "LOWER_BODY_TOP", "SPARK_SIZE",
	"ARC_LIGHT_RANGE", "ONSET_SIZE", "RESIDUE_RISE_MIN", "RESIDUE_RISE_MAX", "SCOUR_Y", "SHED_SIZE_CLASSES",
	"RESIDUE_SIZE_CLASSES", "SCOUR_SIZE_CLASSES"]


func _j(v):
	if v is Color:
		return [snappedf(v.r, 1e-4), snappedf(v.g, 1e-4), snappedf(v.b, 1e-4)]
	if v is Vector3:
		return [snappedf(v.x, 1e-4), snappedf(v.y, 1e-4), snappedf(v.z, 1e-4)]
	if v is Vector2:
		return [snappedf(v.x, 1e-4), snappedf(v.y, 1e-4)]
	if v is float:
		return snappedf(v, 1e-6)
	if v is Array:
		return (v as Array).map(func(x): return _j(x))
	if v is Dictionary:
		var o := {}
		for kk in v:
			o[str(kk)] = _j(v[kk])
		return o
	return v


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	var out := String(args[args.find("--out") + 1])
	var scene = load("res://scenes/barrow_painted.tscn").instantiate()
	root.add_child(scene)
	while not scene.ready_done:
		await process_frame
	var k = scene.knight
	var ch = scene.whirl
	var dual := args.has("--dual")
	if ch == null or dual:
		# the dual-wield barbarian (R-C9-133): bound here the way the Barrow will bind him, on the champion's rig
		ch = load("res://scripts/whirlwind_channel.gd").new()
		scene.add_child(ch)
		ch.setup(scene, k, "original", "clip", "attack", ["weapon_r", "weapon_l"] if dual else ["weapon_r"])
	# --tips bone:x,y,z;bone:x,y,z -- head offsets measured off weapon GLBs this rig does not carry (the JOIN dual
	# barbarian's sword and axe_l: tools/measure_weapon_heads.py), in the bone's local space
	var tip_src := {}
	if args.has("--tips"):
		for spec in String(args[args.find("--tips") + 1]).split(";"):
			var bp := spec.split(":")
			var xyz := bp[1].split(",")
			for f in ch.fxs:
				if String(f.get("grip_bone")) == bp[0]:
					f.blade_head_local = Vector3(float(xyz[0]), float(xyz[1]), float(xyz[2]))
					tip_src[bp[0]] = String(args[args.find("--tips-src") + 1]) if args.has("--tips-src") else "--tips"
	var f0 = ch.fxs[0]
	var consts: Dictionary = f0.get_script().get_script_constant_map()
	var src := {}
	for c in consts:
		if typeof(consts[c]) in [TYPE_INT, TYPE_FLOAT, TYPE_COLOR, TYPE_VECTOR2, TYPE_VECTOR3, TYPE_ARRAY, TYPE_STRING, TYPE_BOOL]:
			src[c] = _j(consts[c])
	var scaled := {}
	for n in LENGTH_VARS:
		scaled[n] = _j(f0.get(n))
	var sk: Skeleton3D = k._skel
	var tips := []
	for f in ch.fxs:
		var hl: Vector3 = f.get("blade_head_local")
		var gb := sk.find_bone(String(f.get("grip_bone")))
		var len_m := 0.0
		if hl != Vector3.ZERO and gb >= 0:
			var rest := sk.global_transform * sk.get_bone_global_rest(gb)
			len_m = (rest * hl - rest.origin).length()
		tips.append({"bone": String(f.get("grip_bone")), "ribbon_only": bool(f.get("ribbon_only")),
			"head_local_bone_space": _j(hl), "length_m": snappedf(len_m, 1e-4),
			"hand_bones": ["LeftHand", "LeftForeArm"] if String(f.get("grip_bone")).ends_with("_l") else ["RightHand", "RightForeArm"],
			"status": ("measured off " + String(tip_src[String(f.get("grip_bone"))])) if tip_src.has(String(f.get("grip_bone")))
				else ("measured off the held weapon mesh" if hl != Vector3.ZERO else "TBD: no weapon mesh on this rig yet -- read when the export lands (rule below)")})
	var wl_spin := {}
	if scene.who == "warlord":
		wl_spin = {"clip_start": "eor_spin_start 0.200 s, accelerating to 1200 deg/s, turns 120 deg",
			"clip_loop": "eor_spin_loop 0.300 s, one CCW revolution (9 x 40 deg keys), closes exactly",
			"omega_deg_s_clip": 1200.0, "source": "wl_e1/export/final_k_eor2/wl_manifest.json eor_spin (R-C9-132 extended arm: fists 0.804 m out at 1.30 m, the haft slid 0.20 m outward through them in these two clips only, the head's far point 1.93 m out at 1.31 m)"}
	if args.has("--spin-clip"):
		wl_spin = JSON.parse_string(String(args[args.find("--spin-clip") + 1]))
	var rep := {
		"_what": "C-9 R-C9-128/R-C9-133: the ported clean-room whirlwind's parameter set for ONE character (reincarnated-godot scripts/wwcr_whirlwind.gd as ported to the painted Barrow: runs/C-9/barrow_full/godot/scripts/whirlwind_fx.gd, generated by tools/port_whirlwind.py; channel timing whirlwind_channel.gd). Dumped by tools/dump_whirlwind_params.gd from the live binding.",
		"character": "dark_knight" if scene.who == "warlord" else ("barbarian_dual" if dual else String(scene.who)),
		"rig_note": String(args[args.find("--rig-note") + 1]) if args.has("--rig-note") else "",
		"rig": String(k.cfg.get("model", "?")),
		"height_m": snappedf(float(f0.get("_s")) * float(consts["H_STAND"]), 1e-4),
		"scale_vs_source": snappedf(float(f0.get("_s")), 1e-6),
		"spin": {"mode": String(ch.mode), "omega_deg_s_source": consts["OMEGA_DEG"], "windup_s": consts["WINDUP_S"],
			"spin_up_s": consts["SPIN_UP_S"], "spin_down_s": consts["SPIN_DOWN_S"], "clip": wl_spin,
			"direction": "CCW seen from above (+yaw); _spin = the weapon head's bearing about the character, unwrapped, in clip mode"},
		"channel": {"tap_s": ch.CHANNEL_S, "held": "stays up while the key/button is held, then spin-down",
			"turn_rate_mul": ch.TURN_RATE_MUL, "moves_while_channelling": true},
		"weapon_tips": tips,
		"weapon_tip_rule": "the grip = the tip bone's origin; the head = the held weapon mesh's farthest vertex from that bone (a vertex belongs to the nearer of weapon_r / weapon_l), at bind, kept in the bone's local space and carried by the bone every frame; the ribbon spans grip.lerp(head, TRAIL_INNER_FRAC +/- the cross-section breathing) -> head",
		"tint": {"name": String(ch.tint), "element_color": _j(ch.TINTS[ch.tint]),
			"ribbon_apex": _j(f0.get("_c_apex")), "ribbon_body": _j(f0.get("_c_body")), "ribbon_tail": _j(f0.get("_c_tail")),
			"tints_available": _j(ch.TINTS),
			"ramp_rule": "set_element keeps the element's HUE only: apex = hsv(h + RAMP_APEX_DH, RAMP_APEX_SV), body = hsv(h + RAMP_BODY_DH, RAMP_BODY_SV), tail = hsv(h + RAMP_TAIL_DH, RAMP_TAIL_SV); red is given at hue 345 deg so the apex lands at 4 deg"},
		"lengths_scaled_m": scaled,
		"source_constants": src,
		"barrow_binding_changes": ["1 every length x scale (height / 1.85)", "2 heights over the character's ground, not y=0",
			"3 rig spin absolute over knight.gd's seat (rig mode)", "4 blade proxy on the weapon bone", "5 pose bone names mapped",
			"6 no light nodes: the ArcLight laid as an additive ground pool (POOL_GAIN 0.11 x energy), spark lights dark",
			"7 drawn after the paint post pass", "8 the arc window held in TIME (10/60 s), not frames",
			"9 the spin from the clip: no rig turn, no arm pose, no re-seat; _spin off the weapon head",
			"10 two blades: a second ribbon-only instance (its ribbon + its apex sheds; every once-per-character layer single)"],
		"glossary": {
			"R_ENGAGE": "the engagement radius, 1.9 x standing height (measured off the native EoR frames); contacts, scuffs and scour live here",
			"R_TRAIL": "the source's blade-tip radius (its greatsword: shoulder 0.21 + arm 0.63 + blade 1.515 m); in clip mode the ribbon follows the REAL weapon head instead",
			"SWEEP_Y / SWEEP_WOBBLE": "the sweep plane height and its helical wobble (+/- sin(spin) x wobble x w)",
			"TRAIL_SAMPLES / trail window": "blade history: 10 samples at 60 fps = 10/60 s (~150 deg at 900 deg/s): an ARC, never a closed ring",
			"TRAIL_INNER_FRAC, XSEC_*": "the ribbon covers the outer ~20 % of the blade; XSEC breathes that inner edge between XSEC_MIN and XSEC_MAX",
			"CORE_* / BODY_*": "two ribbon layers: the core (additive, emissive, the newest CORE_AGE_FRAC of the arc) and the body (alpha-mixed, darkening, the older part); alphas per inner/outer edge",
			"TAPER_MIN_FRAC": "the oldest end of the arc narrows to this fraction of the band",
			"RAMP_*": "the ribbon colour ramp off the tint's hue (apex -> body -> tail)",
			"GUST_*": "Poisson gusts (rate 8-14 /s by channel weight): each surges the core x1.3-1.7 (decay tau) and sheds 2-4 quanta off the apex",
			"ONSET_*": "a ring of quanta thrown out once as the spin rises (from 0.60 to 1.05 x R_ENGAGE)",
			"SHED_*": "ShedQuantum: tinted additive puffs off the apex (gusts) and off the dropped history on spin-down; size classes, life, drag tau, entrain = the fraction of the tip speed they inherit",
			"SPARK_* / MAX_SPARKS": "ContactSpark: tinted, at a contact with a target only (none in the Barrow)",
			"SCUFF_*": "ScuffPuff: NEUTRAL dust at R_ENGAGE on each blade pass (2 per revolution, w > 0.55), thrown along the sweep and dragged to a stop",
			"SCOUR_*": "FloorScour: neutral darkened ground marks laid per pass; persistent (the floor remembers); value tuned to the source's dark floor (venue-coupled)",
			"RESIDUE_*": "RecipientResidue: tinted puffs curling up off a struck target (contacts only)",
			"ARC_LIGHT_*": "the source's light at the tip; in the Barrow a ground pool of that range and colour",
			"spin_up_s / spin_down_s": "measured off the native EoR (two independent rates); the channel weight w ramps 0 -> 1 -> 0 at these",
			"turn_rate_mul": "the GD packet's turn rate while channelling (x0.35)"}}
	var fa := FileAccess.open(out, FileAccess.WRITE)
	fa.store_string(JSON.stringify(rep, " "))
	fa.close()
	print("[wwparams] wrote %s tips=%d" % [out, tips.size()])
	quit(0)
