# R-C9-105: the champion's character slot for the runtime stills/film project (and the scene), regenerate, don't edit.
#   python3 s35_make_pkg.py
import json, os
B = '/Users/admin/Games/reincarnated-collaboration/astra_test_01/burst/runs/C-9/gear_sets/barbarian_gladiator'
FULL = ["girdle", "kilt", "wraps", "greaves", "chest", "wrists", "helm", "pauldron"]
base = {
    "_note": ("THE FREED CHAMPION (Matt R-C9-105, GS-BCH4): the champion body spliced into a copy of his JOIN body "
              "(body/nb-body_champion.glb: every clip byte-identical) and his champion set, each piece a skinned GLB on his 26 "
              "joints. No weapon on him (Matt): the maul is a separate prop, never bound. Generated by scripts/s35_make_pkg.py."),
    "model": "res://models/barbarian_champion/nb-body_champion.glb",
    "gear_dir": "res://models/barbarian_champion",
    "armed_when_pieces": [],
    "morph_rules": {"helmet_on": "helm"},
    "_morph_note": "helmet_on folds his crown hair under the GALEA (gearlib.helmet_on_key, 7035 verts); set while the helm is worn",
    "arm_layer_armed_R": {"action": "idle", "bones": [], "weight": 0.0, "_note": "no weapon, no carry layer (the stills project needs the key)"},
    "clips": {"idle": "idle", "walk": "walk", "run": "run", "whirlwind": "whirlwind"},
}
stacks = dict(base, gear_stacks=[[], ["girdle", "kilt"], ["girdle", "kilt", "wraps", "greaves"],
                                 ["girdle", "kilt", "wraps", "greaves", "chest", "wrists"], FULL,
                                 ["d2_helmet", "d2_bracers", "d2_byrnie", "d2_mantle"]],
              gear_stack_names=["champion body", "+girdle+kilt", "+wraps+greaves", "+chest+wrist guards",
                                "full champion set (+galea +lion pauldron)", "SWAP TEST: his current D2 set on the same body"])
full = dict(base, gear_stacks=[FULL], gear_stack_names=["full champion set"])
os.makedirs(B + '/scene_pkg', exist_ok=True)
json.dump(stacks, open(B + '/scene_pkg/character_champion.json', 'w'), indent=1)
json.dump(full, open(B + '/scene_pkg/character_champion_full.json', 'w'), indent=1)
print("wrote character_champion.json (6 stacks) and character_champion_full.json")
